export * from './reference.js';
export * from './products.js';
export type { ReferenceItem } from './types.js';

import { DEMO_PRODUCTS } from './products.js';
import type {
  JobSearchHit,
  ListingDetail,
  ListingSearchHit,
  ServiceSearchHit,
} from '@only-horses/shared-types';

/**
 * The demo dataset the static preview and the mobile app run on.
 *
 * The preview has no API, no database and no search engine, and the first
 * version of it dealt with that by removing every page that needed one. That
 * was honest and useless: a visitor arriving at a horse marketplace could read
 * the pricing page and the terms of service, and could not look at a horse.
 *
 * So the marketplace pages run on this instead. It is not invented data — it
 * was exported from a running instance with the real endpoints, so every
 * field is the shape the API actually returns and every page renders the same
 * components against the same types. What it is not is live: these twelve
 * listings do not change, nothing here can be contacted, and the banner on
 * every page says so.
 *
 * Seller names and handles are replaced with placeholder stables. The rest —
 * breeds, ages, heights, prices, regions, quality scores — is as generated.
 *
 * It sits in its own package rather than inside the web app because the mobile
 * app needs the same fallback for the same reason, and two copies of a dataset
 * are two datasets: the moment one is re-exported and the other is not, the
 * two platforms are demonstrating different products.
 */

export const DEMO_LISTINGS: ListingSearchHit[] = [
  {
    "id": "5037b874-6362-469a-b8bb-1855e283ee5e",
    "slug": "efsane-lease-seed546",
    "title": "Efsane — 8 yaşında iğdiş",
    "horseName": "Efsane",
    "listingType": "lease",
    "breed": "hanoverian",
    "sex": "gelding",
    "ageYears": 7,
    "heightCm": 167.8,
    "color": "demirkır",
    "disciplines": [
      "hunter"
    ],
    "priceAmount": 1996000,
    "priceCurrency": "TRY",
    "priceEur": 53892,
    "priceType": "fixed",
    "countryCode": "TR",
    "region": "İstanbul",
    "city": "İstanbul",
    "distanceKm": null,
    "sellerVerification": "identity_verified",
    "sellerTrustScore": 57,
    "hasVideo": false,
    "hasXray": false,
    "qualityScore": 100,
    "isBoosted": true,
    "coverImage": null,
    "coverBlurhash": "L6PZfSjE.AyE_3t7t7R**0o#DgR4",
    "publishedAt": "2026-08-13T07:45:53.677Z"
  },
  {
    "id": "32534aac-5cf0-4477-ae50-042f78eb6de0",
    "slug": "mistral-lease-seed27769",
    "title": "Mistral — 5 yaşında aygır",
    "horseName": "Mistral",
    "listingType": "lease",
    "breed": "partbred_arabian",
    "sex": "stallion",
    "ageYears": 5,
    "heightCm": 165,
    "color": "doru",
    "disciplines": [
      "leisure",
      "racing_flat"
    ],
    "priceAmount": 583000,
    "priceCurrency": "TRY",
    "priceEur": 15741,
    "priceType": "fixed",
    "countryCode": "TR",
    "region": "Konya",
    "city": "Konya",
    "distanceKm": null,
    "sellerVerification": "identity_verified",
    "sellerTrustScore": 38,
    "hasVideo": false,
    "hasXray": false,
    "qualityScore": 100,
    "isBoosted": true,
    "coverImage": null,
    "coverBlurhash": "L6PZfSjE.AyE_3t7t7R**0o#DgR4",
    "publishedAt": "2026-08-12T07:48:07.965Z"
  },
  {
    "id": "26b116f9-4a4b-4c40-b5b5-a2abe119bca3",
    "slug": "efsane-sale-seed46686",
    "title": "Efsane — 14 yaşında iğdiş",
    "horseName": "Efsane",
    "listingType": "sale",
    "breed": "trakehner",
    "sex": "gelding",
    "ageYears": 14,
    "heightCm": 150.2,
    "color": "yağız",
    "disciplines": [
      "dressage"
    ],
    "priceAmount": 400000,
    "priceCurrency": "TRY",
    "priceEur": 10800,
    "priceType": "negotiable",
    "countryCode": "TR",
    "region": "İstanbul",
    "city": "İstanbul",
    "distanceKm": null,
    "sellerVerification": "identity_verified",
    "sellerTrustScore": 29,
    "hasVideo": true,
    "hasXray": false,
    "qualityScore": 100,
    "isBoosted": false,
    "coverImage": null,
    "coverBlurhash": "L6PZfSjE.AyE_3t7t7R**0o#DgR4",
    "publishedAt": "2026-08-13T07:49:43.713Z"
  },
  {
    "id": "c74d6d75-ba67-459e-aad1-ba5f41a9d761",
    "slug": "sultan-half-lease-seed43653",
    "title": "Sultan — 14 yaşında kısrak",
    "horseName": "Sultan",
    "listingType": "half_lease",
    "breed": "marwari",
    "sex": "mare",
    "ageYears": 14,
    "heightCm": 151,
    "color": "yağız",
    "disciplines": [
      "leisure",
      "polo",
      "endurance"
    ],
    "priceAmount": 1514000,
    "priceCurrency": "TRY",
    "priceEur": 40878,
    "priceType": "fixed",
    "countryCode": "TR",
    "region": "İstanbul",
    "city": "İstanbul",
    "distanceKm": null,
    "sellerVerification": "identity_verified",
    "sellerTrustScore": 94,
    "hasVideo": false,
    "hasXray": false,
    "qualityScore": 100,
    "isBoosted": false,
    "coverImage": null,
    "coverBlurhash": "L6PZfSjE.AyE_3t7t7R**0o#DgR4",
    "publishedAt": "2026-08-13T07:49:28.073Z"
  },
  {
    "id": "be8b4cfc-8766-4ca9-992b-b74cab099378",
    "slug": "estrella-sale-seed38897",
    "title": "Estrella — 3 yaşında kısrak",
    "horseName": "Estrella",
    "listingType": "sale",
    "breed": "hackney",
    "sex": "mare",
    "ageYears": 2,
    "heightCm": 161.6,
    "color": "doru",
    "disciplines": [
      "leisure"
    ],
    "priceAmount": 0,
    "priceCurrency": "EUR",
    "priceEur": 0,
    "priceType": "on_request",
    "countryCode": "ES",
    "region": "Andalucía",
    "city": "Sevilla",
    "distanceKm": null,
    "sellerVerification": "identity_verified",
    "sellerTrustScore": 53,
    "hasVideo": true,
    "hasXray": true,
    "qualityScore": 100,
    "isBoosted": false,
    "coverImage": null,
    "coverBlurhash": "L6PZfSjE.AyE_3t7t7R**0o#DgR4",
    "publishedAt": "2026-08-13T07:49:04.307Z"
  },
  {
    "id": "497d5e06-35d4-4aee-adb9-b36513b77453",
    "slug": "piaffe-lease-seed37595",
    "title": "Piaffe — 10 yaşında kısrak",
    "horseName": "Piaffe",
    "listingType": "lease",
    "breed": "hessian",
    "sex": "mare",
    "ageYears": 9,
    "heightCm": 175.4,
    "color": "yağız",
    "disciplines": [
      "eventing"
    ],
    "priceAmount": 4646000,
    "priceCurrency": "TRY",
    "priceEur": 125442,
    "priceType": "fixed",
    "countryCode": "TR",
    "region": "İzmir",
    "city": "İzmir",
    "distanceKm": null,
    "sellerVerification": "identity_verified",
    "sellerTrustScore": 68,
    "hasVideo": true,
    "hasXray": false,
    "qualityScore": 100,
    "isBoosted": false,
    "coverImage": null,
    "coverBlurhash": "L6PZfSjE.AyE_3t7t7R**0o#DgR4",
    "publishedAt": "2026-08-13T07:48:58.246Z"
  },
  {
    "id": "ed8fe4e8-894b-4dca-866f-7ca2912ee595",
    "slug": "nova-sale-seed35699",
    "title": "Nova — 10 yaşında iğdiş",
    "horseName": "Nova",
    "listingType": "sale",
    "breed": "morgan",
    "sex": "gelding",
    "ageYears": 9,
    "heightCm": 155.2,
    "color": "siyah",
    "disciplines": [
      "western_pleasure"
    ],
    "priceAmount": 1555000,
    "priceCurrency": "TRY",
    "priceEur": 41985,
    "priceType": "fixed",
    "countryCode": "TR",
    "region": "Ankara",
    "city": "Ankara",
    "distanceKm": null,
    "sellerVerification": "phone_verified",
    "sellerTrustScore": 95,
    "hasVideo": true,
    "hasXray": false,
    "qualityScore": 100,
    "isBoosted": false,
    "coverImage": null,
    "coverBlurhash": "L6PZfSjE.AyE_3t7t7R**0o#DgR4",
    "publishedAt": "2026-08-13T07:48:48.898Z"
  },
  {
    "id": "bb51378e-8637-4a16-801e-3beb6506d076",
    "slug": "simsek-bey-sale-seed35681",
    "title": "Şimşek Bey — 6 yaşında aygır",
    "horseName": "Şimşek Bey",
    "listingType": "sale",
    "breed": "mustang",
    "sex": "stallion",
    "ageYears": 5,
    "heightCm": 177.4,
    "color": "kır",
    "disciplines": [
      "reining",
      "cutting",
      "trail"
    ],
    "priceAmount": 278000,
    "priceCurrency": "TRY",
    "priceEur": 7506,
    "priceType": "negotiable",
    "countryCode": "TR",
    "region": "İstanbul",
    "city": "İstanbul",
    "distanceKm": null,
    "sellerVerification": "identity_verified",
    "sellerTrustScore": 38,
    "hasVideo": true,
    "hasXray": true,
    "qualityScore": 100,
    "isBoosted": false,
    "coverImage": null,
    "coverBlurhash": "L6PZfSjE.AyE_3t7t7R**0o#DgR4",
    "publishedAt": "2026-08-13T07:48:48.803Z"
  },
  {
    "id": "0c6cd95c-47f8-4713-86ec-80c5be1ecd4d",
    "slug": "piaffe-sale-seed35209",
    "title": "Piaffe — 18 yaşında iğdiş",
    "horseName": "Piaffe",
    "listingType": "sale",
    "breed": "arabian_egyptian",
    "sex": "gelding",
    "ageYears": 18,
    "heightCm": 163.1,
    "color": "demirkır",
    "disciplines": [
      "endurance"
    ],
    "priceAmount": 709000,
    "priceCurrency": "TRY",
    "priceEur": 19143,
    "priceType": "fixed",
    "countryCode": "TR",
    "region": "İzmir",
    "city": "İzmir",
    "distanceKm": null,
    "sellerVerification": "identity_verified",
    "sellerTrustScore": 85,
    "hasVideo": true,
    "hasXray": false,
    "qualityScore": 100,
    "isBoosted": false,
    "coverImage": null,
    "coverBlurhash": "L6PZfSjE.AyE_3t7t7R**0o#DgR4",
    "publishedAt": "2026-08-13T07:48:46.335Z"
  },
  {
    "id": "4cec06fb-aa8e-4235-8045-54996b69d27f",
    "slug": "quixote-sale-seed25333",
    "title": "Quixote — 9 yaşında iğdiş",
    "horseName": "Quixote",
    "listingType": "sale",
    "breed": "appaloosa",
    "sex": "gelding",
    "ageYears": 9,
    "heightCm": 169.2,
    "color": "kestane",
    "disciplines": [
      "cutting"
    ],
    "priceAmount": 1307000,
    "priceCurrency": "TRY",
    "priceEur": 35289,
    "priceType": "fixed",
    "countryCode": "TR",
    "region": "Antalya",
    "city": "Antalya",
    "distanceKm": null,
    "sellerVerification": "identity_verified",
    "sellerTrustScore": 35,
    "hasVideo": false,
    "hasXray": false,
    "qualityScore": 100,
    "isBoosted": false,
    "coverImage": null,
    "coverBlurhash": "L6PZfSjE.AyE_3t7t7R**0o#DgR4",
    "publishedAt": "2026-08-13T07:47:55.776Z"
  },
  {
    "id": "53610b79-ea84-4c17-b2f7-200e228ff1b0",
    "slug": "zumrut-sale-seed22112",
    "title": "Zümrüt — 17 yaşında aygır",
    "horseName": "Zümrüt",
    "listingType": "sale",
    "breed": "trakya",
    "sex": "stallion",
    "ageYears": 17,
    "heightCm": 177.4,
    "color": "kestane",
    "disciplines": [
      "leisure",
      "rahvan",
      "cirit"
    ],
    "priceAmount": 454000,
    "priceCurrency": "TRY",
    "priceEur": 12258,
    "priceType": "fixed",
    "countryCode": "TR",
    "region": "İstanbul",
    "city": "İstanbul",
    "distanceKm": null,
    "sellerVerification": "identity_verified",
    "sellerTrustScore": 31,
    "hasVideo": false,
    "hasXray": true,
    "qualityScore": 100,
    "isBoosted": false,
    "coverImage": null,
    "coverBlurhash": "L6PZfSjE.AyE_3t7t7R**0o#DgR4",
    "publishedAt": "2026-08-13T07:47:40.112Z"
  },
  {
    "id": "5e4204dc-af8e-490f-944b-97417695320a",
    "slug": "luna-sale-seed19803",
    "title": "Luna — 17 yaşında iğdiş",
    "horseName": "Luna",
    "listingType": "sale",
    "breed": "pony_of_americas",
    "sex": "gelding",
    "ageYears": 16,
    "heightCm": 120.2,
    "color": "kula",
    "disciplines": [
      "equitation"
    ],
    "priceAmount": 3000,
    "priceCurrency": "EUR",
    "priceEur": 3000,
    "priceType": "negotiable",
    "countryCode": "ES",
    "region": "Andalucía",
    "city": "Sevilla",
    "distanceKm": null,
    "sellerVerification": "identity_verified",
    "sellerTrustScore": 62,
    "hasVideo": true,
    "hasXray": false,
    "qualityScore": 100,
    "isBoosted": false,
    "coverImage": null,
    "coverBlurhash": "L6PZfSjE.AyE_3t7t7R**0o#DgR4",
    "publishedAt": "2026-08-13T07:47:28.950Z"
  }
];

export const DEMO_LISTING_DETAIL: Record<string, ListingDetail> = {
  "efsane-lease-seed546": {
    "id": "5037b874-6362-469a-b8bb-1855e283ee5e",
    "slug": "efsane-lease-seed546",
    "horse_id": "8d0dd4cf-659d-47e9-89ad-22b7530f5e25",
    "seller_profile_id": "79b610ed-8cbf-453c-9072-116e85bb4514",
    "seller_org_id": null,
    "type": "lease",
    "status": "active",
    "title": "Efsane — 8 yaşında iğdiş",
    "summary": "orta seviye, hunter için uygun",
    "description": "Efsane, İstanbul bölgesinde. orta seviyede eğitimli, hunter çalışıyor. Sakin mizaçlı, ayak bakımı ve aşıları güncel. Ciddi alıcılar için deneme binişi ve satın alma öncesi veteriner muayenesi mümkündür. Nakliye konusunda yardımcı olabiliriz.",
    "price_amount": "1996000.00",
    "price_currency": "TRY",
    "price_type": "fixed",
    "price_period": null,
    "vat_included": null,
    "trial_allowed": true,
    "ppe_welcome": false,
    "transport_help": true,
    "suitable_for": [],
    "country_code": "TR",
    "region": "İstanbul",
    "city": "İstanbul",
    "location": "0101000020E61000000A686CCE7DF43C40E2291FD05E9A4440",
    "view_count": 643,
    "save_count": 9,
    "inquiry_count": 4,
    "quality_score": 100,
    "is_boosted": true,
    "boost_expires_at": "2026-08-20T07:45:53.677Z",
    "published_at": "2026-08-13T07:45:53.677Z",
    "expires_at": "2026-10-12T07:45:53.677Z",
    "under_offer_since": null,
    "closed_at": null,
    "closed_reason": null,
    "sold_to_profile_id": null,
    "rejection_reason": null,
    "legal_hold": false,
    "created_at": "2026-08-13T07:45:53.677Z",
    "updated_at": "2026-08-13T08:29:34.716Z",
    "horse_name": "Efsane",
    "horse_slug": "efsane-seed546",
    "sex": "gelding",
    "color": "demirkır",
    "height_cm": "167.8",
    "date_of_birth": "2018-10-23",
    "birth_year_estimated": false,
    "disciplines": [
      "hunter"
    ],
    "training_level": "orta",
    "rider_level_min": "ileri",
    "horse_about": "8 yaşında iğdiş. orta seviyede, hunter için uygun. Düzenli nal ve aşı takibi yapılıyor. Deneme binişine açığız, satın alma öncesi veteriner muayenesini memnuniyetle karşılarız.",
    "temperament_notes": null,
    "training_notes": null,
    "breed_id": "hanoverian",
    "visibility_health": "on_request",
    "visibility_pedigree": "public",
    "visibility_documents": "on_request",
    "breed_name_tr": "Hanover",
    "breed_name_en": "Hanoverian",
    "seller_handle": "uzunyayla",
    "seller_name": "Uzunyayla Harası",
    "seller_trust_score": 57,
    "seller_verification": "identity_verified",
    "seller_response_rate": "0.775",
    "isOwner": false
  },
  "mistral-lease-seed27769": {
    "id": "32534aac-5cf0-4477-ae50-042f78eb6de0",
    "slug": "mistral-lease-seed27769",
    "horse_id": "60851d0c-22ae-4017-a4b3-c1e1962f9a95",
    "seller_profile_id": "48653d2e-2ea6-40a7-861e-31addbddda9a",
    "seller_org_id": null,
    "type": "lease",
    "status": "active",
    "title": "Mistral — 5 yaşında aygır",
    "summary": "başlangıç seviye, leisure için uygun",
    "description": "Mistral, Konya bölgesinde. başlangıç seviyede eğitimli, leisure, racing_flat çalışıyor. Sakin mizaçlı, ayak bakımı ve aşıları güncel. Ciddi alıcılar için deneme binişi ve satın alma öncesi veteriner muayenesi mümkündür. Nakliye konusunda yardımcı olabiliriz.",
    "price_amount": "583000.00",
    "price_currency": "TRY",
    "price_type": "fixed",
    "price_period": null,
    "vat_included": null,
    "trial_allowed": true,
    "ppe_welcome": true,
    "transport_help": false,
    "suitable_for": [],
    "country_code": "TR",
    "region": "Konya",
    "city": "Konya",
    "location": "0101000020E6100000907128F6A9394040728A74939EF14240",
    "view_count": 700,
    "save_count": 52,
    "inquiry_count": 11,
    "quality_score": 100,
    "is_boosted": true,
    "boost_expires_at": "2026-08-20T07:48:07.965Z",
    "published_at": "2026-08-12T07:48:07.965Z",
    "expires_at": "2026-10-11T07:48:07.965Z",
    "under_offer_since": null,
    "closed_at": null,
    "closed_reason": null,
    "sold_to_profile_id": null,
    "rejection_reason": null,
    "legal_hold": false,
    "created_at": "2026-08-13T07:48:07.965Z",
    "updated_at": "2026-08-13T08:29:34.788Z",
    "horse_name": "Mistral",
    "horse_slug": "mistral-seed27769",
    "sex": "stallion",
    "color": "doru",
    "height_cm": "165.0",
    "date_of_birth": "2021-03-07",
    "birth_year_estimated": false,
    "disciplines": [
      "leisure",
      "racing_flat"
    ],
    "training_level": "başlangıç",
    "rider_level_min": "yeni başlayan",
    "horse_about": "5 yaşında aygır. başlangıç seviyede, leisure ve racing_flat için uygun. Düzenli nal ve aşı takibi yapılıyor. Deneme binişine açığız, satın alma öncesi veteriner muayenesini memnuniyetle karşılarız.",
    "temperament_notes": null,
    "training_notes": null,
    "breed_id": "partbred_arabian",
    "visibility_health": "on_request",
    "visibility_pedigree": "public",
    "visibility_documents": "on_request",
    "breed_name_tr": "Melez Arap",
    "breed_name_en": "Part-bred Arabian",
    "seller_handle": "ege-at",
    "seller_name": "Ege At Çiftliği",
    "seller_trust_score": 38,
    "seller_verification": "identity_verified",
    "seller_response_rate": "0.692",
    "isOwner": false
  },
  "efsane-sale-seed46686": {
    "id": "26b116f9-4a4b-4c40-b5b5-a2abe119bca3",
    "slug": "efsane-sale-seed46686",
    "horse_id": "bed0f1c3-6876-4b58-a723-af4df6a0506c",
    "seller_profile_id": "b5c266c4-5cbd-4c0e-8481-4c3132405c1c",
    "seller_org_id": null,
    "type": "sale",
    "status": "active",
    "title": "Efsane — 14 yaşında iğdiş",
    "summary": "başlangıç seviye, dressage için uygun",
    "description": "Efsane, İstanbul bölgesinde. başlangıç seviyede eğitimli, dressage çalışıyor. Sakin mizaçlı, ayak bakımı ve aşıları güncel. Ciddi alıcılar için deneme binişi ve satın alma öncesi veteriner muayenesi mümkündür. Nakliye konusunda yardımcı olabiliriz.",
    "price_amount": "400000.00",
    "price_currency": "TRY",
    "price_type": "negotiable",
    "price_period": null,
    "vat_included": null,
    "trial_allowed": true,
    "ppe_welcome": false,
    "transport_help": true,
    "suitable_for": [],
    "country_code": "TR",
    "region": "İstanbul",
    "city": "İstanbul",
    "location": "0101000020E61000000AE8F2A6C0D43C40E2291B8BFAA04440",
    "view_count": 6,
    "save_count": 36,
    "inquiry_count": 22,
    "quality_score": 100,
    "is_boosted": false,
    "boost_expires_at": null,
    "published_at": "2026-08-13T07:49:43.713Z",
    "expires_at": "2026-10-12T07:49:43.713Z",
    "under_offer_since": null,
    "closed_at": null,
    "closed_reason": null,
    "sold_to_profile_id": null,
    "rejection_reason": null,
    "legal_hold": false,
    "created_at": "2026-08-13T07:49:43.713Z",
    "updated_at": "2026-08-13T08:29:34.774Z",
    "horse_name": "Efsane",
    "horse_slug": "efsane-seed46686",
    "sex": "gelding",
    "color": "yağız",
    "height_cm": "150.2",
    "date_of_birth": "2012-02-03",
    "birth_year_estimated": false,
    "disciplines": [
      "dressage"
    ],
    "training_level": "başlangıç",
    "rider_level_min": "orta",
    "horse_about": "14 yaşında iğdiş. başlangıç seviyede, dressage için uygun. Düzenli nal ve aşı takibi yapılıyor. Deneme binişine açığız, satın alma öncesi veteriner muayenesini memnuniyetle karşılarız.",
    "temperament_notes": null,
    "training_notes": null,
    "breed_id": "trakehner",
    "visibility_health": "on_request",
    "visibility_pedigree": "public",
    "visibility_documents": "on_request",
    "breed_name_tr": "Trakehner",
    "breed_name_en": "Trakehner",
    "seller_handle": "anadolu-binicilik",
    "seller_name": "Anadolu Binicilik",
    "seller_trust_score": 29,
    "seller_verification": "identity_verified",
    "seller_response_rate": null,
    "isOwner": false
  },
  "sultan-half-lease-seed43653": {
    "id": "c74d6d75-ba67-459e-aad1-ba5f41a9d761",
    "slug": "sultan-half-lease-seed43653",
    "horse_id": "cba86aeb-7fef-48fd-a97f-d47d73886d9e",
    "seller_profile_id": "b1269ba3-fe99-4b79-880f-439cb7e11314",
    "seller_org_id": null,
    "type": "half_lease",
    "status": "active",
    "title": "Sultan — 14 yaşında kısrak",
    "summary": "yarışma seviye, leisure için uygun",
    "description": "Sultan, İstanbul bölgesinde. yarışma seviyede eğitimli, leisure, polo, endurance çalışıyor. Sakin mizaçlı, ayak bakımı ve aşıları güncel. Ciddi alıcılar için deneme binişi ve satın alma öncesi veteriner muayenesi mümkündür. Nakliye konusunda yardımcı olabiliriz.",
    "price_amount": "1514000.00",
    "price_currency": "TRY",
    "price_type": "fixed",
    "price_period": null,
    "vat_included": null,
    "trial_allowed": true,
    "ppe_welcome": true,
    "transport_help": true,
    "suitable_for": [],
    "country_code": "TR",
    "region": "İstanbul",
    "city": "İstanbul",
    "location": "0101000020E61000000AE8819139BF3C40E2E998BFE3984440",
    "view_count": 855,
    "save_count": 59,
    "inquiry_count": 3,
    "quality_score": 100,
    "is_boosted": false,
    "boost_expires_at": null,
    "published_at": "2026-08-13T07:49:28.073Z",
    "expires_at": "2026-10-12T07:49:28.073Z",
    "under_offer_since": null,
    "closed_at": null,
    "closed_reason": null,
    "sold_to_profile_id": null,
    "rejection_reason": null,
    "legal_hold": false,
    "created_at": "2026-08-13T07:49:28.073Z",
    "updated_at": "2026-08-13T08:29:34.791Z",
    "horse_name": "Sultan",
    "horse_slug": "sultan-seed43653",
    "sex": "mare",
    "color": "yağız",
    "height_cm": "151.0",
    "date_of_birth": "2012-01-22",
    "birth_year_estimated": false,
    "disciplines": [
      "leisure",
      "polo",
      "endurance"
    ],
    "training_level": "yarışma",
    "rider_level_min": "ileri",
    "horse_about": "14 yaşında kısrak. yarışma seviyede, leisure ve polo ve endurance için uygun. Düzenli nal ve aşı takibi yapılıyor. Deneme binişine açığız, satın alma öncesi veteriner muayenesini memnuniyetle karşılarız.",
    "temperament_notes": null,
    "training_notes": null,
    "breed_id": "marwari",
    "visibility_health": "on_request",
    "visibility_pedigree": "public",
    "visibility_documents": "on_request",
    "breed_name_tr": "Marwari",
    "breed_name_en": "Marwari",
    "seller_handle": "kapadokya",
    "seller_name": "Kapadokya Atçılık",
    "seller_trust_score": 94,
    "seller_verification": "identity_verified",
    "seller_response_rate": null,
    "isOwner": false
  },
  "estrella-sale-seed38897": {
    "id": "be8b4cfc-8766-4ca9-992b-b74cab099378",
    "slug": "estrella-sale-seed38897",
    "horse_id": "3977392a-9d5e-48ce-a5a6-35a5b56703fb",
    "seller_profile_id": "f876b2de-a863-43e1-a512-80ba8ec4a647",
    "seller_org_id": null,
    "type": "sale",
    "status": "active",
    "title": "Estrella — 3 yaşında kısrak",
    "summary": "orta seviye, leisure için uygun",
    "description": "Estrella, Sevilla bölgesinde. orta seviyede eğitimli, leisure çalışıyor. Sakin mizaçlı, ayak bakımı ve aşıları güncel. Ciddi alıcılar için deneme binişi ve satın alma öncesi veteriner muayenesi mümkündür. Nakliye konusunda yardımcı olabiliriz.",
    "price_amount": null,
    "price_currency": "EUR",
    "price_type": "on_request",
    "price_period": null,
    "vat_included": null,
    "trial_allowed": false,
    "ppe_welcome": true,
    "transport_help": false,
    "suitable_for": [],
    "country_code": "ES",
    "region": "Andalucía",
    "city": "Sevilla",
    "location": "0101000020E6100000E3A54F85631A18C0D26F1B77FDA34240",
    "view_count": 250,
    "save_count": 40,
    "inquiry_count": 20,
    "quality_score": 100,
    "is_boosted": false,
    "boost_expires_at": null,
    "published_at": "2026-08-13T07:49:04.307Z",
    "expires_at": "2026-10-12T07:49:04.307Z",
    "under_offer_since": null,
    "closed_at": null,
    "closed_reason": null,
    "sold_to_profile_id": null,
    "rejection_reason": null,
    "legal_hold": false,
    "created_at": "2026-08-13T07:49:04.307Z",
    "updated_at": "2026-08-13T08:29:34.717Z",
    "horse_name": "Estrella",
    "horse_slug": "estrella-seed38897",
    "sex": "mare",
    "color": "doru",
    "height_cm": "161.6",
    "date_of_birth": "2023-08-26",
    "birth_year_estimated": false,
    "disciplines": [
      "leisure"
    ],
    "training_level": "orta",
    "rider_level_min": "ileri",
    "horse_about": "3 yaşında kısrak. orta seviyede, leisure için uygun. Düzenli nal ve aşı takibi yapılıyor. Deneme binişine açığız, satın alma öncesi veteriner muayenesini memnuniyetle karşılarız.",
    "temperament_notes": null,
    "training_notes": null,
    "breed_id": "hackney",
    "visibility_health": "on_request",
    "visibility_pedigree": "public",
    "visibility_documents": "on_request",
    "breed_name_tr": "Hackney",
    "breed_name_en": "Hackney",
    "seller_handle": "marmara-hara",
    "seller_name": "Marmara Hara",
    "seller_trust_score": 53,
    "seller_verification": "identity_verified",
    "seller_response_rate": null,
    "isOwner": false
  },
  "piaffe-lease-seed37595": {
    "id": "497d5e06-35d4-4aee-adb9-b36513b77453",
    "slug": "piaffe-lease-seed37595",
    "horse_id": "e9de4260-73f5-4a36-8881-b7fed34b69fd",
    "seller_profile_id": "0f3c1de6-47b4-47dc-a879-1c21ab2e846f",
    "seller_org_id": null,
    "type": "lease",
    "status": "active",
    "title": "Piaffe — 10 yaşında kısrak",
    "summary": "yarışma seviye, eventing için uygun",
    "description": "Piaffe, İzmir bölgesinde. yarışma seviyede eğitimli, eventing çalışıyor. Sakin mizaçlı, ayak bakımı ve aşıları güncel. Ciddi alıcılar için deneme binişi ve satın alma öncesi veteriner muayenesi mümkündür. Nakliye konusunda yardımcı olabiliriz.",
    "price_amount": "4646000.00",
    "price_currency": "TRY",
    "price_type": "fixed",
    "price_period": null,
    "vat_included": null,
    "trial_allowed": true,
    "ppe_welcome": true,
    "transport_help": false,
    "suitable_for": [],
    "country_code": "TR",
    "region": "İzmir",
    "city": "İzmir",
    "location": "0101000020E61000006ADEE48A1E5B3B4058A8BE16632F4340",
    "view_count": 400,
    "save_count": 9,
    "inquiry_count": 13,
    "quality_score": 100,
    "is_boosted": false,
    "boost_expires_at": null,
    "published_at": "2026-08-13T07:48:58.246Z",
    "expires_at": "2026-10-12T07:48:58.246Z",
    "under_offer_since": null,
    "closed_at": null,
    "closed_reason": null,
    "sold_to_profile_id": null,
    "rejection_reason": null,
    "legal_hold": false,
    "created_at": "2026-08-13T07:48:58.246Z",
    "updated_at": "2026-08-13T08:29:34.784Z",
    "horse_name": "Piaffe",
    "horse_slug": "piaffe-seed37595",
    "sex": "mare",
    "color": "yağız",
    "height_cm": "175.4",
    "date_of_birth": "2016-09-28",
    "birth_year_estimated": false,
    "disciplines": [
      "eventing"
    ],
    "training_level": "yarışma",
    "rider_level_min": "orta",
    "horse_about": "10 yaşında kısrak. yarışma seviyede, eventing için uygun. Düzenli nal ve aşı takibi yapılıyor. Deneme binişine açığız, satın alma öncesi veteriner muayenesini memnuniyetle karşılarız.",
    "temperament_notes": null,
    "training_notes": null,
    "breed_id": "hessian",
    "visibility_health": "on_request",
    "visibility_pedigree": "public",
    "visibility_documents": "on_request",
    "breed_name_tr": "Hessen",
    "breed_name_en": "Hessian",
    "seller_handle": "toros",
    "seller_name": "Toros Binicilik",
    "seller_trust_score": 68,
    "seller_verification": "identity_verified",
    "seller_response_rate": "0.884",
    "isOwner": false
  },
  "nova-sale-seed35699": {
    "id": "ed8fe4e8-894b-4dca-866f-7ca2912ee595",
    "slug": "nova-sale-seed35699",
    "horse_id": "b825ba7f-12a5-4ea1-a991-873ea688cc75",
    "seller_profile_id": "d5b048d4-00e6-46fd-ad65-4af2c05d1b5b",
    "seller_org_id": null,
    "type": "sale",
    "status": "active",
    "title": "Nova — 10 yaşında iğdiş",
    "summary": "yarışma seviye, western_pleasure için uygun",
    "description": "Nova, Ankara bölgesinde. yarışma seviyede eğitimli, western_pleasure çalışıyor. Sakin mizaçlı, ayak bakımı ve aşıları güncel. Ciddi alıcılar için deneme binişi ve satın alma öncesi veteriner muayenesi mümkündür. Nakliye konusunda yardımcı olabiliriz.",
    "price_amount": "1555000.00",
    "price_currency": "TRY",
    "price_type": "fixed",
    "price_period": null,
    "vat_included": null,
    "trial_allowed": true,
    "ppe_welcome": true,
    "transport_help": true,
    "suitable_for": [],
    "country_code": "TR",
    "region": "Ankara",
    "city": "Ankara",
    "location": "0101000020E610000083EFE51D127140400FCB5CD37C144440",
    "view_count": 678,
    "save_count": 25,
    "inquiry_count": 2,
    "quality_score": 100,
    "is_boosted": false,
    "boost_expires_at": null,
    "published_at": "2026-08-13T07:48:48.898Z",
    "expires_at": "2026-10-12T07:48:48.898Z",
    "under_offer_since": null,
    "closed_at": null,
    "closed_reason": null,
    "sold_to_profile_id": null,
    "rejection_reason": null,
    "legal_hold": false,
    "created_at": "2026-08-13T07:48:48.898Z",
    "updated_at": "2026-08-13T08:29:34.715Z",
    "horse_name": "Nova",
    "horse_slug": "nova-seed35699",
    "sex": "gelding",
    "color": "siyah",
    "height_cm": "155.2",
    "date_of_birth": "2016-11-23",
    "birth_year_estimated": false,
    "disciplines": [
      "western_pleasure"
    ],
    "training_level": "yarışma",
    "rider_level_min": "profesyonel",
    "horse_about": "10 yaşında iğdiş. yarışma seviyede, western_pleasure için uygun. Düzenli nal ve aşı takibi yapılıyor. Deneme binişine açığız, satın alma öncesi veteriner muayenesini memnuniyetle karşılarız.",
    "temperament_notes": null,
    "training_notes": null,
    "breed_id": "morgan",
    "visibility_health": "public",
    "visibility_pedigree": "public",
    "visibility_documents": "on_request",
    "breed_name_tr": "Morgan",
    "breed_name_en": "Morgan",
    "seller_handle": "ankara-at",
    "seller_name": "Ankara At Merkezi",
    "seller_trust_score": 95,
    "seller_verification": "phone_verified",
    "seller_response_rate": "0.962",
    "isOwner": false
  },
  "simsek-bey-sale-seed35681": {
    "id": "bb51378e-8637-4a16-801e-3beb6506d076",
    "slug": "simsek-bey-sale-seed35681",
    "horse_id": "cd99f991-02b5-42e9-bc88-c8dc40d4dcec",
    "seller_profile_id": "c6b30fc3-6bc7-489b-ac09-b8bf1daedab5",
    "seller_org_id": null,
    "type": "sale",
    "status": "active",
    "title": "Şimşek Bey — 6 yaşında aygır",
    "summary": "orta seviye, reining için uygun",
    "description": "Şimşek Bey, İstanbul bölgesinde. orta seviyede eğitimli, reining, cutting, trail çalışıyor. Sakin mizaçlı, ayak bakımı ve aşıları güncel. Ciddi alıcılar için deneme binişi ve satın alma öncesi veteriner muayenesi mümkündür. Nakliye konusunda yardımcı olabiliriz.",
    "price_amount": "278000.00",
    "price_currency": "TRY",
    "price_type": "negotiable",
    "price_period": null,
    "vat_included": null,
    "trial_allowed": true,
    "ppe_welcome": true,
    "transport_help": true,
    "suitable_for": [],
    "country_code": "TR",
    "region": "İstanbul",
    "city": "İstanbul",
    "location": "0101000020E61000000A6848D529CD3C40E269BC37E87D4440",
    "view_count": 279,
    "save_count": 45,
    "inquiry_count": 23,
    "quality_score": 100,
    "is_boosted": false,
    "boost_expires_at": null,
    "published_at": "2026-08-13T07:48:48.803Z",
    "expires_at": "2026-10-12T07:48:48.803Z",
    "under_offer_since": null,
    "closed_at": null,
    "closed_reason": null,
    "sold_to_profile_id": null,
    "rejection_reason": null,
    "legal_hold": false,
    "created_at": "2026-08-13T07:48:48.803Z",
    "updated_at": "2026-08-13T08:29:34.796Z",
    "horse_name": "Şimşek Bey",
    "horse_slug": "simsek-bey-seed35681",
    "sex": "stallion",
    "color": "kır",
    "height_cm": "177.4",
    "date_of_birth": "2020-10-08",
    "birth_year_estimated": false,
    "disciplines": [
      "reining",
      "cutting",
      "trail"
    ],
    "training_level": "orta",
    "rider_level_min": "orta",
    "horse_about": "6 yaşında aygır. orta seviyede, reining ve cutting ve trail için uygun. Düzenli nal ve aşı takibi yapılıyor. Deneme binişine açığız, satın alma öncesi veteriner muayenesini memnuniyetle karşılarız.",
    "temperament_notes": null,
    "training_notes": null,
    "breed_id": "mustang",
    "visibility_health": "public",
    "visibility_pedigree": "public",
    "visibility_documents": "on_request",
    "breed_name_tr": "Mustang",
    "breed_name_en": "Mustang",
    "seller_handle": "bursa-hara",
    "seller_name": "Bursa Hara",
    "seller_trust_score": 38,
    "seller_verification": "identity_verified",
    "seller_response_rate": null,
    "isOwner": false
  },
  "piaffe-sale-seed35209": {
    "id": "0c6cd95c-47f8-4713-86ec-80c5be1ecd4d",
    "slug": "piaffe-sale-seed35209",
    "horse_id": "63274513-4eb1-435c-bde6-1bae97bbe736",
    "seller_profile_id": "4f7e0026-c3b3-42a0-be43-17be858f771c",
    "seller_org_id": null,
    "type": "sale",
    "status": "active",
    "title": "Piaffe — 18 yaşında iğdiş",
    "summary": "ileri seviye, endurance için uygun",
    "description": "Piaffe, İzmir bölgesinde. ileri seviyede eğitimli, endurance çalışıyor. Sakin mizaçlı, ayak bakımı ve aşıları güncel. Ciddi alıcılar için deneme binişi ve satın alma öncesi veteriner muayenesi mümkündür. Nakliye konusunda yardımcı olabiliriz.",
    "price_amount": "709000.00",
    "price_currency": "TRY",
    "price_type": "fixed",
    "price_period": null,
    "vat_included": null,
    "trial_allowed": true,
    "ppe_welcome": true,
    "transport_help": true,
    "suitable_for": [],
    "country_code": "TR",
    "region": "İzmir",
    "city": "İzmir",
    "location": "0101000020E61000006A5EE0CABBE83A405868360B8F404340",
    "view_count": 245,
    "save_count": 58,
    "inquiry_count": 12,
    "quality_score": 100,
    "is_boosted": false,
    "boost_expires_at": null,
    "published_at": "2026-08-13T07:48:46.335Z",
    "expires_at": "2026-10-12T07:48:46.335Z",
    "under_offer_since": null,
    "closed_at": null,
    "closed_reason": null,
    "sold_to_profile_id": null,
    "rejection_reason": null,
    "legal_hold": false,
    "created_at": "2026-08-13T07:48:46.335Z",
    "updated_at": "2026-08-13T08:29:34.787Z",
    "horse_name": "Piaffe",
    "horse_slug": "piaffe-seed35209",
    "sex": "gelding",
    "color": "demirkır",
    "height_cm": "163.1",
    "date_of_birth": "2008-04-05",
    "birth_year_estimated": false,
    "disciplines": [
      "endurance"
    ],
    "training_level": "ileri",
    "rider_level_min": "yeni başlayan",
    "horse_about": "18 yaşında iğdiş. ileri seviyede, endurance için uygun. Düzenli nal ve aşı takibi yapılıyor. Deneme binişine açığız, satın alma öncesi veteriner muayenesini memnuniyetle karşılarız.",
    "temperament_notes": null,
    "training_notes": null,
    "breed_id": "arabian_egyptian",
    "visibility_health": "on_request",
    "visibility_pedigree": "public",
    "visibility_documents": "on_request",
    "breed_name_tr": "Mısır Arap Atı",
    "breed_name_en": "Straight Egyptian Arabian",
    "seller_handle": "konya-yilki",
    "seller_name": "Konya Yılkı",
    "seller_trust_score": 85,
    "seller_verification": "identity_verified",
    "seller_response_rate": "0.933",
    "isOwner": false
  },
  "quixote-sale-seed25333": {
    "id": "4cec06fb-aa8e-4235-8045-54996b69d27f",
    "slug": "quixote-sale-seed25333",
    "horse_id": "2fb9ba20-68ed-428b-9dff-3800ee08390d",
    "seller_profile_id": "a5a1282b-0523-460a-a8e0-0e27508bfbd8",
    "seller_org_id": null,
    "type": "sale",
    "status": "active",
    "title": "Quixote — 9 yaşında iğdiş",
    "summary": "yarışma seviye, cutting için uygun",
    "description": "Quixote, Antalya bölgesinde. yarışma seviyede eğitimli, cutting çalışıyor. Sakin mizaçlı, ayak bakımı ve aşıları güncel. Ciddi alıcılar için deneme binişi ve satın alma öncesi veteriner muayenesi mümkündür. Nakliye konusunda yardımcı olabiliriz.",
    "price_amount": "1307000.00",
    "price_currency": "TRY",
    "price_type": "fixed",
    "price_period": null,
    "vat_included": null,
    "trial_allowed": true,
    "ppe_welcome": true,
    "transport_help": false,
    "suitable_for": [],
    "country_code": "TR",
    "region": "Antalya",
    "city": "Antalya",
    "location": "0101000020E61000009F3CBDB865DF3E4026A44344558A4240",
    "view_count": 112,
    "save_count": 28,
    "inquiry_count": 24,
    "quality_score": 100,
    "is_boosted": false,
    "boost_expires_at": null,
    "published_at": "2026-08-13T07:47:55.776Z",
    "expires_at": "2026-10-12T07:47:55.776Z",
    "under_offer_since": null,
    "closed_at": null,
    "closed_reason": null,
    "sold_to_profile_id": null,
    "rejection_reason": null,
    "legal_hold": false,
    "created_at": "2026-08-13T07:47:55.776Z",
    "updated_at": "2026-08-13T08:29:34.881Z",
    "horse_name": "Quixote",
    "horse_slug": "quixote-seed25333",
    "sex": "gelding",
    "color": "kestane",
    "height_cm": "169.2",
    "date_of_birth": "2017-08-10",
    "birth_year_estimated": false,
    "disciplines": [
      "cutting"
    ],
    "training_level": "yarışma",
    "rider_level_min": "yeni başlayan",
    "horse_about": "9 yaşında iğdiş. yarışma seviyede, cutting için uygun. Düzenli nal ve aşı takibi yapılıyor. Deneme binişine açığız, satın alma öncesi veteriner muayenesini memnuniyetle karşılarız.",
    "temperament_notes": null,
    "training_notes": null,
    "breed_id": "appaloosa",
    "visibility_health": "public",
    "visibility_pedigree": "public",
    "visibility_documents": "on_request",
    "breed_name_tr": "Appaloosa",
    "breed_name_en": "Appaloosa",
    "seller_handle": "izmir-binicilik",
    "seller_name": "İzmir Binicilik",
    "seller_trust_score": 35,
    "seller_verification": "identity_verified",
    "seller_response_rate": null,
    "isOwner": false
  },
  "zumrut-sale-seed22112": {
    "id": "53610b79-ea84-4c17-b2f7-200e228ff1b0",
    "slug": "zumrut-sale-seed22112",
    "horse_id": "c6566135-29c0-4e09-b200-e550c7f93de0",
    "seller_profile_id": "b1ea0a2e-346f-4230-be23-d6bbd2c1bb3f",
    "seller_org_id": null,
    "type": "sale",
    "status": "active",
    "title": "Zümrüt — 17 yaşında aygır",
    "summary": "yarışma seviye, leisure için uygun",
    "description": "Zümrüt, İstanbul bölgesinde. yarışma seviyede eğitimli, leisure, rahvan, cirit çalışıyor. Sakin mizaçlı, ayak bakımı ve aşıları güncel. Ciddi alıcılar için deneme binişi ve satın alma öncesi veteriner muayenesi mümkündür. Nakliye konusunda yardımcı olabiliriz.",
    "price_amount": "454000.00",
    "price_currency": "TRY",
    "price_type": "fixed",
    "price_period": null,
    "vat_included": null,
    "trial_allowed": true,
    "ppe_welcome": true,
    "transport_help": false,
    "suitable_for": [],
    "country_code": "TR",
    "region": "İstanbul",
    "city": "İstanbul",
    "location": "0101000020E61000000A686A2A04253D40E2A9F4464D7B4440",
    "view_count": 638,
    "save_count": 48,
    "inquiry_count": 13,
    "quality_score": 100,
    "is_boosted": false,
    "boost_expires_at": null,
    "published_at": "2026-08-13T07:47:40.112Z",
    "expires_at": "2026-10-12T07:47:40.112Z",
    "under_offer_since": null,
    "closed_at": null,
    "closed_reason": null,
    "sold_to_profile_id": null,
    "rejection_reason": null,
    "legal_hold": false,
    "created_at": "2026-08-13T07:47:40.112Z",
    "updated_at": "2026-08-13T08:29:34.782Z",
    "horse_name": "Zümrüt",
    "horse_slug": "zumrut-seed22112",
    "sex": "stallion",
    "color": "kestane",
    "height_cm": "177.4",
    "date_of_birth": "2009-03-01",
    "birth_year_estimated": false,
    "disciplines": [
      "leisure",
      "rahvan",
      "cirit"
    ],
    "training_level": "yarışma",
    "rider_level_min": "profesyonel",
    "horse_about": "17 yaşında aygır. yarışma seviyede, leisure ve rahvan ve cirit için uygun. Düzenli nal ve aşı takibi yapılıyor. Deneme binişine açığız, satın alma öncesi veteriner muayenesini memnuniyetle karşılarız.",
    "temperament_notes": null,
    "training_notes": null,
    "breed_id": "trakya",
    "visibility_health": "public",
    "visibility_pedigree": "public",
    "visibility_documents": "on_request",
    "breed_name_tr": "Trakya",
    "breed_name_en": "Trakya",
    "seller_handle": "antalya-at",
    "seller_name": "Antalya At Çiftliği",
    "seller_trust_score": 31,
    "seller_verification": "identity_verified",
    "seller_response_rate": "0.669",
    "isOwner": false
  },
  "luna-sale-seed19803": {
    "id": "5e4204dc-af8e-490f-944b-97417695320a",
    "slug": "luna-sale-seed19803",
    "horse_id": "0ebafbde-6ade-4c25-aece-e0e7cb3977ab",
    "seller_profile_id": "c42690e4-54ae-42ae-aac6-fec78d535108",
    "seller_org_id": null,
    "type": "sale",
    "status": "active",
    "title": "Luna — 17 yaşında iğdiş",
    "summary": "temel seviye, equitation için uygun",
    "description": "Luna, Sevilla bölgesinde. temel seviyede eğitimli, equitation çalışıyor. Sakin mizaçlı, ayak bakımı ve aşıları güncel. Ciddi alıcılar için deneme binişi ve satın alma öncesi veteriner muayenesi mümkündür. Nakliye konusunda yardımcı olabiliriz.",
    "price_amount": "3000.00",
    "price_currency": "EUR",
    "price_type": "negotiable",
    "price_period": null,
    "vat_included": null,
    "trial_allowed": true,
    "ppe_welcome": true,
    "transport_help": false,
    "suitable_for": [],
    "country_code": "ES",
    "region": "Andalucía",
    "city": "Sevilla",
    "location": "0101000020E6100000E3A5C307839218C0D26FD14474AF4240",
    "view_count": 371,
    "save_count": 40,
    "inquiry_count": 2,
    "quality_score": 100,
    "is_boosted": false,
    "boost_expires_at": null,
    "published_at": "2026-08-13T07:47:28.950Z",
    "expires_at": "2026-10-12T07:47:28.950Z",
    "under_offer_since": null,
    "closed_at": null,
    "closed_reason": null,
    "sold_to_profile_id": null,
    "rejection_reason": null,
    "legal_hold": false,
    "created_at": "2026-08-13T07:47:28.950Z",
    "updated_at": "2026-08-13T08:29:34.774Z",
    "horse_name": "Luna",
    "horse_slug": "luna-seed19803",
    "sex": "gelding",
    "color": "kula",
    "height_cm": "120.2",
    "date_of_birth": "2009-09-19",
    "birth_year_estimated": false,
    "disciplines": [
      "equitation"
    ],
    "training_level": "temel",
    "rider_level_min": "profesyonel",
    "horse_about": "17 yaşında iğdiş. temel seviyede, equitation için uygun. Düzenli nal ve aşı takibi yapılıyor. Deneme binişine açığız, satın alma öncesi veteriner muayenesini memnuniyetle karşılarız.",
    "temperament_notes": null,
    "training_notes": null,
    "breed_id": "pony_of_americas",
    "visibility_health": "on_request",
    "visibility_pedigree": "public",
    "visibility_documents": "on_request",
    "breed_name_tr": "Amerika Midillisi",
    "breed_name_en": "Pony of the Americas",
    "seller_handle": "trakya-hara",
    "seller_name": "Trakya Hara",
    "seller_trust_score": 62,
    "seller_verification": "identity_verified",
    "seller_response_rate": "0.987",
    "isOwner": false
  }
} as unknown as Record<string, ListingDetail>;

export const DEMO_SERVICES: ServiceSearchHit[] = [
  {
    "id": "1fcfc500-810d-44bd-9847-6521bfe89bb0",
    "slug": "yurt-ici-at-nakliyesi-3",
    "title": "Yurt ici at nakliyesi",
    "category": "transport",
    "providerId": "f468c0e2-f6d2-448e-9e50-54410e25580d",
    "providerName": "Kayseri Hara",
    "providerVerification": "identity_verified",
    "providerTrustScore": 45,
    "providerAvatar": null,
    "organizationName": null,
    "priceMin": null,
    "priceMax": null,
    "priceUnit": null,
    "currency": "EUR",
    "countryCode": "TR",
    "region": null,
    "city": "Kayseri",
    "distanceKm": null,
    "isMobile": true,
    "serviceRadiusKm": null,
    "ratingAverage": null,
    "ratingCount": 0,
    "publishedAt": "2026-08-13T09:02:49.199Z"
  },
  {
    "id": "e9d511ab-e55d-4430-abde-5a5ef98e2271",
    "slug": "mobil-nalbant-hizmeti-3",
    "title": "Mobil nalbant hizmeti",
    "category": "farrier",
    "providerId": "8e8fd110-e932-4fd2-822b-6b1cf067500c",
    "providerName": "Nalbant Usta",
    "providerVerification": "identity_verified",
    "providerTrustScore": 45,
    "providerAvatar": null,
    "organizationName": null,
    "priceMin": 800,
    "priceMax": 1500,
    "priceUnit": "session",
    "currency": "TRY",
    "countryCode": "TR",
    "region": "Ankara",
    "city": "Ankara",
    "distanceKm": null,
    "isMobile": true,
    "serviceRadiusKm": 120,
    "ratingAverage": null,
    "ratingCount": 0,
    "publishedAt": "2026-08-13T09:02:49.157Z"
  },
  {
    "id": "1945a1ef-41c6-4e83-9902-a5c5bf9d7ec2",
    "slug": "yurt-ici-at-nakliyesi-2",
    "title": "Yurt ici at nakliyesi",
    "category": "transport",
    "providerId": "9634218c-a04b-4226-9fc1-1d03a089e6a7",
    "providerName": "Kayseri Hara",
    "providerVerification": "identity_verified",
    "providerTrustScore": 45,
    "providerAvatar": null,
    "organizationName": null,
    "priceMin": null,
    "priceMax": null,
    "priceUnit": null,
    "currency": "EUR",
    "countryCode": "TR",
    "region": null,
    "city": "Kayseri",
    "distanceKm": null,
    "isMobile": true,
    "serviceRadiusKm": null,
    "ratingAverage": null,
    "ratingCount": 0,
    "publishedAt": "2026-08-13T09:02:44.283Z"
  },
  {
    "id": "04f6581a-0f25-4e3b-9877-6cf64574d78d",
    "slug": "mobil-nalbant-hizmeti-2",
    "title": "Mobil nalbant hizmeti",
    "category": "farrier",
    "providerId": "1cc1a161-0d6b-47f8-8235-ed9131d18aee",
    "providerName": "Nalbant Usta",
    "providerVerification": "identity_verified",
    "providerTrustScore": 45,
    "providerAvatar": null,
    "organizationName": null,
    "priceMin": 800,
    "priceMax": 1500,
    "priceUnit": "session",
    "currency": "TRY",
    "countryCode": "TR",
    "region": "Ankara",
    "city": "Ankara",
    "distanceKm": null,
    "isMobile": true,
    "serviceRadiusKm": 120,
    "ratingAverage": null,
    "ratingCount": 0,
    "publishedAt": "2026-08-13T09:02:44.239Z"
  },
  {
    "id": "58bb4c33-f7dd-470f-8c73-49722b3a4c35",
    "slug": "yurt-ici-at-nakliyesi",
    "title": "Yurt ici at nakliyesi",
    "category": "transport",
    "providerId": "57849362-1e9e-45ae-96cc-208f12fe1aa8",
    "providerName": "Kayseri Hara",
    "providerVerification": "identity_verified",
    "providerTrustScore": 45,
    "providerAvatar": null,
    "organizationName": null,
    "priceMin": null,
    "priceMax": null,
    "priceUnit": null,
    "currency": "EUR",
    "countryCode": "TR",
    "region": null,
    "city": "Kayseri",
    "distanceKm": null,
    "isMobile": true,
    "serviceRadiusKm": null,
    "ratingAverage": null,
    "ratingCount": 0,
    "publishedAt": "2026-08-13T08:38:46.157Z"
  },
  {
    "id": "e195246c-bce5-4538-a312-06e983f0ed52",
    "slug": "mobil-nalbant-hizmeti",
    "title": "Mobil nalbant hizmeti",
    "category": "farrier",
    "providerId": "d08e523d-c671-4ee7-b105-cc6602d91dea",
    "providerName": "Nalbant Usta",
    "providerVerification": "identity_verified",
    "providerTrustScore": 45,
    "providerAvatar": null,
    "organizationName": null,
    "priceMin": 800,
    "priceMax": 1500,
    "priceUnit": "session",
    "currency": "TRY",
    "countryCode": "TR",
    "region": "Ankara",
    "city": "Ankara",
    "distanceKm": null,
    "isMobile": true,
    "serviceRadiusKm": 120,
    "ratingAverage": null,
    "ratingCount": 0,
    "publishedAt": "2026-08-13T08:38:46.113Z"
  }
];

export const DEMO_JOBS: JobSearchHit[] = [
  {
    "id": "a4e20191-5e08-42d5-bf1a-7781b0b24f74",
    "slug": "nalbant-yardimcisi-3",
    "title": "Nalbant yardimcisi",
    "jobType": "part_time",
    "rolesNeeded": [
      "farrier"
    ],
    "organizationName": null,
    "organizationLogo": null,
    "posterName": "Nalbant Usta",
    "countryCode": "TR",
    "region": null,
    "city": "Ankara",
    "distanceKm": null,
    "salaryMin": null,
    "salaryMax": null,
    "salaryCurrency": null,
    "salaryPeriod": null,
    "salaryMonthlyEur": null,
    "accommodation": null,
    "mealsIncluded": false,
    "visaSupport": false,
    "experienceYearsMin": null,
    "applicationCount": 0,
    "publishedAt": "2026-08-13T09:02:46.860Z"
  },
  {
    "id": "e2b1e99b-dfdb-4ba9-a3e0-100d056461d9",
    "slug": "nalbant-yardimcisi-2",
    "title": "Nalbant yardimcisi",
    "jobType": "part_time",
    "rolesNeeded": [
      "farrier"
    ],
    "organizationName": null,
    "organizationLogo": null,
    "posterName": "Nalbant Usta",
    "countryCode": "TR",
    "region": null,
    "city": "Ankara",
    "distanceKm": null,
    "salaryMin": null,
    "salaryMax": null,
    "salaryCurrency": null,
    "salaryPeriod": null,
    "salaryMonthlyEur": null,
    "accommodation": null,
    "mealsIncluded": false,
    "visaSupport": false,
    "experienceYearsMin": null,
    "applicationCount": 0,
    "publishedAt": "2026-08-13T09:02:41.599Z"
  },
  {
    "id": "fff3ce36-a85b-46c1-a95b-ea7776b4dfe7",
    "slug": "nalbant-yardimcisi",
    "title": "Nalbant yardimcisi",
    "jobType": "part_time",
    "rolesNeeded": [
      "farrier"
    ],
    "organizationName": null,
    "organizationLogo": null,
    "posterName": "Nalbant Usta",
    "countryCode": "TR",
    "region": null,
    "city": "Ankara",
    "distanceKm": null,
    "salaryMin": null,
    "salaryMax": null,
    "salaryCurrency": null,
    "salaryPeriod": null,
    "salaryMonthlyEur": null,
    "accommodation": null,
    "mealsIncluded": false,
    "visaSupport": false,
    "experienceYearsMin": null,
    "applicationCount": 0,
    "publishedAt": "2026-08-13T08:38:41.317Z"
  }
];

/** §18.2 S06's filter controls, over a dataset small enough to filter in the browser. */
export const DEMO_LISTING_TYPES = Array.from(
  new Set(DEMO_LISTINGS.map((listing) => listing.listingType)),
);

export const DEMO_REGIONS = Array.from(
  new Set(DEMO_LISTINGS.map((listing) => listing.region).filter(Boolean) as string[]),
).sort();

/**
 * The sellers behind the demo, as public profiles.
 *
 * Derived rather than exported: every field here already appears on a listing
 * or a product in this file, so the preview's profile page shows the same
 * placeholder yards the rest of the preview does and no additional claim about
 * anyone is invented. Without it the seller link on every listing and product
 * card in the preview is a 404 — which is how the last version of this page
 * ended up not existing at all.
 *
 * What is missing is what the demo genuinely does not carry: bios, roles,
 * review counts and response times belong to the profile endpoint, not to a
 * search hit, so they are null and the page renders its "—" rather than a
 * number nobody measured.
 */
export interface DemoProfile {
  id: string;
  handle: string;
  displayName: string;
  bio: string | null;
  city: string | null;
  region: string | null;
  verificationLevel: string;
  trustScore: number;
  responseRate: number | null;
  responseTimeMins: number | null;
  reviewCount: number;
  reviewAverage: number | null;
  roles: { role: string }[];
  trustChips: string[];
  createdAt: string;
}

export const DEMO_PROFILES: Record<string, DemoProfile> = (() => {
  const table: Record<string, DemoProfile> = {};

  for (const listing of Object.values(DEMO_LISTING_DETAIL)) {
    if (table[listing.seller_handle]) continue;

    table[listing.seller_handle] = {
      id: listing.seller_profile_id,
      handle: listing.seller_handle,
      displayName: listing.seller_name,
      bio: null,
      city: listing.city,
      region: listing.region,
      verificationLevel: listing.seller_verification,
      trustScore: listing.seller_trust_score,
      responseRate:
        listing.seller_response_rate === null ? null : Number(listing.seller_response_rate),
      responseTimeMins: null,
      reviewCount: 0,
      reviewAverage: null,
      roles: [],
      trustChips: [],
      createdAt: listing.published_at ?? new Date(0).toISOString(),
    };
  }

  for (const product of DEMO_PRODUCTS) {
    if (table[product.sellerHandle]) continue;

    table[product.sellerHandle] = {
      id: product.id,
      handle: product.sellerHandle,
      displayName: product.sellerName,
      bio: null,
      city: product.city,
      region: product.region,
      verificationLevel: product.sellerVerification,
      trustScore: product.sellerTrustScore,
      responseRate: null,
      responseTimeMins: null,
      reviewCount: 0,
      reviewAverage: null,
      roles: [],
      trustChips: [],
      createdAt: product.publishedAt ?? new Date(0).toISOString(),
    };
  }

  return table;
})();
