import type { ProductSearchHit } from '@only-horses/shared-types';

import type { ReferenceItem } from './types.js';

/**
 * The product catalogue the demo runs on, exported from a running instance.
 *
 * Real rows through the real endpoints, so every field is the shape the API
 * returns. Sellers are placeholder yards; the rest — categories, brands,
 * sizes, prices, units — is as seeded.
 */
export const DEMO_PRODUCTS: ProductSearchHit[] = [
  {
    "id": "b9a775ea-d82b-46d9-be7e-0774435dc7f7",
    "slug": "eyer-alti-3-adet-dresaj-kesim-msuirr48",
    "title": "Eyer altı — 3 adet, dresaj kesim",
    "category": "saddle_pad",
    "categoryName": "Eyer altı",
    "parentCategory": "tack",
    "brand": null,
    "model": null,
    "sizeLabel": null,
    "condition": "good",
    "priceAmount": 900,
    "priceCurrency": "TRY",
    "priceType": "fixed",
    "priceUnit": "item",
    "quantity": 3,
    "delivery": "shipping",
    "countryCode": "TR",
    "region": "İzmir",
    "city": "İzmir",
    "sellerHandle": "saraciye-atolyesi",
    "sellerName": "Saraciye Atölyesi",
    "sellerVerification": "none",
    "sellerTrustScore": 0,
    "coverImage": null,
    "isBoosted": false,
    "publishedAt": "2026-08-15T15:17:08.750Z"
  },
  {
    "id": "e3c35778-6b9e-42ff-a7f7-0074f61a770e",
    "slug": "nalbant-takimi-komple-msuirr3w",
    "title": "Nalbant takımı — komple",
    "category": "farrier_tools",
    "categoryName": "Nal ve tırnak bakımı",
    "parentCategory": "horse_care",
    "brand": null,
    "model": null,
    "sizeLabel": null,
    "condition": "used",
    "priceAmount": 8900,
    "priceCurrency": "TRY",
    "priceType": "fixed",
    "priceUnit": "item",
    "quantity": 1,
    "delivery": "both",
    "countryCode": "TR",
    "region": "Kayseri",
    "city": "Kayseri",
    "sellerHandle": "ege-ahir-sistemleri",
    "sellerName": "Ege Ahır Sistemleri",
    "sellerVerification": "none",
    "sellerTrustScore": 0,
    "coverImage": null,
    "isBoosted": false,
    "publishedAt": "2026-08-15T15:17:08.740Z"
  },
  {
    "id": "4b31e7d6-789d-40f1-af80-bf013d935884",
    "slug": "2-atlik-romork-2019-model-msuirr3l",
    "title": "2 atlık römork — 2019 model",
    "category": "trailer",
    "categoryName": "Römork ve at kamyonu",
    "parentCategory": "transport",
    "brand": null,
    "model": null,
    "sizeLabel": null,
    "condition": "good",
    "priceAmount": 485000,
    "priceCurrency": "TRY",
    "priceType": "negotiable",
    "priceUnit": "item",
    "quantity": 1,
    "delivery": "pickup",
    "countryCode": "TR",
    "region": "Ankara",
    "city": "Ankara",
    "sellerHandle": "anadolu-yem",
    "sellerName": "Anadolu Yem",
    "sellerVerification": "none",
    "sellerTrustScore": 0,
    "coverImage": null,
    "isBoosted": false,
    "publishedAt": "2026-08-15T15:17:08.728Z"
  },
  {
    "id": "be63619f-55e3-42d6-9ad4-5657fef87c29",
    "slug": "longe-kayisi-ve-kamci-takimi-msuirr3c",
    "title": "Longe kayışı ve kamçı takımı",
    "category": "lunging",
    "categoryName": "Longe ekipmanı",
    "parentCategory": "arena",
    "brand": null,
    "model": null,
    "sizeLabel": null,
    "condition": "good",
    "priceAmount": 1250,
    "priceCurrency": "TRY",
    "priceType": "fixed",
    "priceUnit": "item",
    "quantity": 1,
    "delivery": "shipping",
    "countryCode": "TR",
    "region": "Bursa",
    "city": "Bursa",
    "sellerHandle": "saraciye-atolyesi",
    "sellerName": "Saraciye Atölyesi",
    "sellerVerification": "none",
    "sellerTrustScore": 0,
    "coverImage": null,
    "isBoosted": false,
    "publishedAt": "2026-08-15T15:17:08.717Z"
  },
  {
    "id": "46e3c396-fdcd-4c97-95fd-0bb9da8c8312",
    "slug": "engel-seti-6-ayak-12-sirik-msuirr30",
    "title": "Engel seti — 6 ayak, 12 sırık",
    "category": "jumps",
    "categoryName": "Engel ve sırık",
    "parentCategory": "arena",
    "brand": null,
    "model": null,
    "sizeLabel": null,
    "condition": "good",
    "priceAmount": 28000,
    "priceCurrency": "TRY",
    "priceType": "negotiable",
    "priceUnit": "item",
    "quantity": 1,
    "delivery": "pickup",
    "countryCode": "TR",
    "region": "İstanbul",
    "city": "İstanbul",
    "sellerHandle": "ege-ahir-sistemleri",
    "sellerName": "Ege Ahır Sistemleri",
    "sellerVerification": "none",
    "sellerTrustScore": 0,
    "coverImage": null,
    "isBoosted": false,
    "publishedAt": "2026-08-15T15:17:08.707Z"
  },
  {
    "id": "33fa5a1e-707f-4b22-af15-b489a5c85aec",
    "slug": "otomatik-suluk-paslanmaz-msuirr2n",
    "title": "Otomatik suluk — paslanmaz",
    "category": "waterer",
    "categoryName": "Suluk ve yemlik",
    "parentCategory": "stable",
    "brand": null,
    "model": null,
    "sizeLabel": null,
    "condition": "new",
    "priceAmount": 2650,
    "priceCurrency": "TRY",
    "priceType": "fixed",
    "priceUnit": "item",
    "quantity": 20,
    "delivery": "both",
    "countryCode": "TR",
    "region": "Ankara",
    "city": "Ankara",
    "sellerHandle": "anadolu-yem",
    "sellerName": "Anadolu Yem",
    "sellerVerification": "none",
    "sellerTrustScore": 0,
    "coverImage": null,
    "isBoosted": false,
    "publishedAt": "2026-08-15T15:17:08.695Z"
  },
  {
    "id": "9728119f-6aeb-4a05-8dfc-8c0de82fe072",
    "slug": "galvaniz-boks-paneli-3-5-m-msuirr2c",
    "title": "Galvaniz boks paneli 3.5 m",
    "category": "stalls",
    "categoryName": "Boks ve panel",
    "parentCategory": "stable",
    "brand": null,
    "model": null,
    "sizeLabel": null,
    "condition": "good",
    "priceAmount": 34000,
    "priceCurrency": "TRY",
    "priceType": "fixed",
    "priceUnit": "item",
    "quantity": 8,
    "delivery": "pickup",
    "countryCode": "TR",
    "region": "İzmir",
    "city": "İzmir",
    "sellerHandle": "saraciye-atolyesi",
    "sellerName": "Saraciye Atölyesi",
    "sellerVerification": "none",
    "sellerTrustScore": 0,
    "coverImage": null,
    "isBoosted": false,
    "publishedAt": "2026-08-15T15:17:08.683Z"
  },
  {
    "id": "925db7a0-f65f-43f2-9654-ae0a2e005c41",
    "slug": "ahsap-cit-diregi-emprenyeli-2-4-m-msuirr1z",
    "title": "Ahşap çit direği — emprenyeli 2.4 m",
    "category": "fencing",
    "categoryName": "Çit ve tel",
    "parentCategory": "stable",
    "brand": null,
    "model": null,
    "sizeLabel": null,
    "condition": "new",
    "priceAmount": 285,
    "priceCurrency": "TRY",
    "priceType": "fixed",
    "priceUnit": "item",
    "quantity": 300,
    "delivery": "pickup",
    "countryCode": "TR",
    "region": "İzmir",
    "city": "İzmir",
    "sellerHandle": "ege-ahir-sistemleri",
    "sellerName": "Ege Ahır Sistemleri",
    "sellerVerification": "none",
    "sellerTrustScore": 0,
    "coverImage": null,
    "isBoosted": false,
    "publishedAt": "2026-08-15T15:17:08.671Z"
  },
  {
    "id": "51a85e8e-a0a2-47df-87f1-a04c260a5199",
    "slug": "elektrikli-cit-teli-500-m-makara-msuirr1n",
    "title": "Elektrikli çit teli — 500 m makara",
    "category": "fencing",
    "categoryName": "Çit ve tel",
    "parentCategory": "stable",
    "brand": null,
    "model": null,
    "sizeLabel": null,
    "condition": "new",
    "priceAmount": 1450,
    "priceCurrency": "TRY",
    "priceType": "fixed",
    "priceUnit": "item",
    "quantity": 6,
    "delivery": "both",
    "countryCode": "TR",
    "region": "İzmir",
    "city": "İzmir",
    "sellerHandle": "anadolu-yem",
    "sellerName": "Anadolu Yem",
    "sellerVerification": "none",
    "sellerTrustScore": 0,
    "coverImage": null,
    "isBoosted": false,
    "publishedAt": "2026-08-15T15:17:08.657Z"
  },
  {
    "id": "6f81d51d-792e-4752-b3ba-952cc756c252",
    "slug": "eklem-takviyesi-3-kg-msuirr1b",
    "title": "Eklem takviyesi — 3 kg",
    "category": "supplements",
    "categoryName": "Takviye ve vitamin",
    "parentCategory": "horse_care",
    "brand": null,
    "model": null,
    "sizeLabel": null,
    "condition": "new",
    "priceAmount": 2100,
    "priceCurrency": "TRY",
    "priceType": "fixed",
    "priceUnit": "item",
    "quantity": 1,
    "delivery": "shipping",
    "countryCode": "TR",
    "region": "İstanbul",
    "city": "İstanbul",
    "sellerHandle": "saraciye-atolyesi",
    "sellerName": "Saraciye Atölyesi",
    "sellerVerification": "none",
    "sellerTrustScore": 0,
    "coverImage": null,
    "isBoosted": false,
    "publishedAt": "2026-08-15T15:17:08.646Z"
  },
  {
    "id": "4cb895f0-4cd6-4d5b-95db-692f938642e1",
    "slug": "talas-altlik-sikistirilmis-balya-msuirr0y",
    "title": "Talaş altlık — sıkıştırılmış balya",
    "category": "bedding",
    "categoryName": "Altlık ve talaş",
    "parentCategory": "feed",
    "brand": null,
    "model": null,
    "sizeLabel": null,
    "condition": "new",
    "priceAmount": 310,
    "priceCurrency": "TRY",
    "priceType": "fixed",
    "priceUnit": "bale",
    "quantity": 400,
    "delivery": "both",
    "countryCode": "TR",
    "region": "Bursa",
    "city": "Bursa",
    "sellerHandle": "ege-ahir-sistemleri",
    "sellerName": "Ege Ahır Sistemleri",
    "sellerVerification": "none",
    "sellerTrustScore": 0,
    "coverImage": null,
    "isBoosted": false,
    "publishedAt": "2026-08-15T15:17:08.634Z"
  },
  {
    "id": "f1bbce93-f936-4f92-9906-c08e8c0a20d4",
    "slug": "at-yemi-25-kg-cuval-performans-msuirr0n",
    "title": "At yemi — 25 kg çuval, performans",
    "category": "grain",
    "categoryName": "Yem ve kesif yem",
    "parentCategory": "feed",
    "brand": "Anadolu Yem",
    "model": null,
    "sizeLabel": null,
    "condition": "new",
    "priceAmount": 680,
    "priceCurrency": "TRY",
    "priceType": "fixed",
    "priceUnit": "sack",
    "quantity": 200,
    "delivery": "both",
    "countryCode": "TR",
    "region": "Konya",
    "city": "Konya",
    "sellerHandle": "anadolu-yem",
    "sellerName": "Anadolu Yem",
    "sellerVerification": "none",
    "sellerTrustScore": 0,
    "coverImage": null,
    "isBoosted": false,
    "publishedAt": "2026-08-15T15:17:08.622Z"
  },
  {
    "id": "18fdf127-f7fa-4f1d-8171-47b03c19163d",
    "slug": "birinci-bicim-yonca-balya-msuirr0c",
    "title": "Birinci biçim yonca — balya",
    "category": "hay",
    "categoryName": "Kuru ot ve yonca",
    "parentCategory": "feed",
    "brand": null,
    "model": null,
    "sizeLabel": null,
    "condition": "new",
    "priceAmount": 420,
    "priceCurrency": "TRY",
    "priceType": "fixed",
    "priceUnit": "bale",
    "quantity": 600,
    "delivery": "pickup",
    "countryCode": "TR",
    "region": "Konya",
    "city": "Konya",
    "sellerHandle": "saraciye-atolyesi",
    "sellerName": "Saraciye Atölyesi",
    "sellerVerification": "none",
    "sellerTrustScore": 0,
    "coverImage": null,
    "isBoosted": false,
    "publishedAt": "2026-08-15T15:17:08.610Z"
  },
  {
    "id": "b1c3f37b-1dce-43af-9e92-2bd68e90b1fa",
    "slug": "timar-seti-firca-kasagi-tarak-msuirqzz",
    "title": "Tımar seti — fırça, kaşağı, tarak",
    "category": "grooming",
    "categoryName": "Tımar malzemeleri",
    "parentCategory": "horse_care",
    "brand": null,
    "model": null,
    "sizeLabel": null,
    "condition": "good",
    "priceAmount": 950,
    "priceCurrency": "TRY",
    "priceType": "fixed",
    "priceUnit": "item",
    "quantity": 1,
    "delivery": "shipping",
    "countryCode": "TR",
    "region": "Ankara",
    "city": "Ankara",
    "sellerHandle": "ege-ahir-sistemleri",
    "sellerName": "Ege Ahır Sistemleri",
    "sellerVerification": "none",
    "sellerTrustScore": 0,
    "coverImage": null,
    "isBoosted": false,
    "publishedAt": "2026-08-15T15:17:08.599Z"
  },
  {
    "id": "d84b637c-74d3-4805-aaba-51b7998d59e1",
    "slug": "tendon-ve-fetlock-boot-takimi-msuirqzn",
    "title": "Tendon ve fetlock boot takımı",
    "category": "horse_boots",
    "categoryName": "At tozluğu ve bandaj",
    "parentCategory": "horse_care",
    "brand": null,
    "model": null,
    "sizeLabel": "Cob",
    "condition": "good",
    "priceAmount": 1850,
    "priceCurrency": "TRY",
    "priceType": "fixed",
    "priceUnit": "item",
    "quantity": 1,
    "delivery": "shipping",
    "countryCode": "TR",
    "region": "İzmir",
    "city": "İzmir",
    "sellerHandle": "anadolu-yem",
    "sellerName": "Anadolu Yem",
    "sellerVerification": "none",
    "sellerTrustScore": 0,
    "coverImage": null,
    "isBoosted": false,
    "publishedAt": "2026-08-15T15:17:08.586Z"
  },
  {
    "id": "f24ea9fb-66b9-4236-bb61-93a95892f880",
    "slug": "kislik-cul-145-cm-300g-dolgu-msuirqzc",
    "title": "Kışlık çul 145 cm — 300g dolgu",
    "category": "rugs",
    "categoryName": "Battaniye ve çul",
    "parentCategory": "horse_care",
    "brand": "Horseware",
    "model": null,
    "sizeLabel": "145 cm",
    "condition": "good",
    "priceAmount": 3600,
    "priceCurrency": "TRY",
    "priceType": "fixed",
    "priceUnit": "item",
    "quantity": 1,
    "delivery": "both",
    "countryCode": "TR",
    "region": "Konya",
    "city": "Konya",
    "sellerHandle": "saraciye-atolyesi",
    "sellerName": "Saraciye Atölyesi",
    "sellerVerification": "none",
    "sellerTrustScore": 0,
    "coverImage": null,
    "isBoosted": false,
    "publishedAt": "2026-08-15T15:17:08.575Z"
  },
  {
    "id": "5303a27e-b494-41a7-84b1-dda710842b9e",
    "slug": "ariat-binici-cizmesi-41-numara-msuirqyz",
    "title": "Ariat binici çizmesi 41 numara",
    "category": "riding_boots",
    "categoryName": "Binici çizmesi",
    "parentCategory": "rider",
    "brand": "Ariat",
    "model": null,
    "sizeLabel": "41",
    "condition": "good",
    "priceAmount": 4800,
    "priceCurrency": "TRY",
    "priceType": "negotiable",
    "priceUnit": "item",
    "quantity": 1,
    "delivery": "shipping",
    "countryCode": "TR",
    "region": "Antalya",
    "city": "Antalya",
    "sellerHandle": "ege-ahir-sistemleri",
    "sellerName": "Ege Ahır Sistemleri",
    "sellerVerification": "none",
    "sellerTrustScore": 0,
    "coverImage": null,
    "isBoosted": false,
    "publishedAt": "2026-08-15T15:17:08.563Z"
  },
  {
    "id": "38d7963b-2ed5-419a-8c9f-c427f1273951",
    "slug": "samshield-miss-shield-kask-57-msuirqyl",
    "title": "Samshield Miss Shield kask 57",
    "category": "helmet",
    "categoryName": "Kask",
    "parentCategory": "rider",
    "brand": "Samshield",
    "model": null,
    "sizeLabel": "57",
    "condition": "like_new",
    "priceAmount": 14500,
    "priceCurrency": "TRY",
    "priceType": "fixed",
    "priceUnit": "item",
    "quantity": 1,
    "delivery": "both",
    "countryCode": "TR",
    "region": "İstanbul",
    "city": "İstanbul",
    "sellerHandle": "anadolu-yem",
    "sellerName": "Anadolu Yem",
    "sellerVerification": "none",
    "sellerTrustScore": 0,
    "coverImage": null,
    "isBoosted": false,
    "publishedAt": "2026-08-15T15:17:08.549Z"
  },
  {
    "id": "e078dd98-8a18-4868-880d-d47765b243ca",
    "slug": "sprenger-cift-kirik-gem-125-mm-msuirqy8",
    "title": "Sprenger çift kırık gem 125 mm",
    "category": "bit",
    "categoryName": "Gem",
    "parentCategory": "tack",
    "brand": "Sprenger",
    "model": null,
    "sizeLabel": "125 mm",
    "condition": "good",
    "priceAmount": 2400,
    "priceCurrency": "TRY",
    "priceType": "fixed",
    "priceUnit": "item",
    "quantity": 1,
    "delivery": "shipping",
    "countryCode": "TR",
    "region": "Bursa",
    "city": "Bursa",
    "sellerHandle": "saraciye-atolyesi",
    "sellerName": "Saraciye Atölyesi",
    "sellerVerification": "none",
    "sellerTrustScore": 0,
    "coverImage": null,
    "isBoosted": false,
    "publishedAt": "2026-08-15T15:17:08.536Z"
  },
  {
    "id": "b16c6569-a067-42d9-81c2-c3cc0940383a",
    "slug": "deri-baslik-ve-dizgin-takimi-cob-msuirqxr",
    "title": "Deri başlık ve dizgin takımı — cob",
    "category": "bridle",
    "categoryName": "Başlık ve dizgin",
    "parentCategory": "tack",
    "brand": "Kavalkade",
    "model": null,
    "sizeLabel": "Cob",
    "condition": "new",
    "priceAmount": 3200,
    "priceCurrency": "TRY",
    "priceType": "fixed",
    "priceUnit": "item",
    "quantity": 1,
    "delivery": "shipping",
    "countryCode": "TR",
    "region": "Ankara",
    "city": "Ankara",
    "sellerHandle": "ege-ahir-sistemleri",
    "sellerName": "Ege Ahır Sistemleri",
    "sellerVerification": "none",
    "sellerTrustScore": 0,
    "coverImage": null,
    "isBoosted": false,
    "publishedAt": "2026-08-15T15:17:08.521Z"
  },
  {
    "id": "7a3965a3-dc05-4897-8095-3cc7e1f39349",
    "slug": "antares-dresaj-eyeri-17-inc-msuirqxb",
    "title": "Antares Dresaj Eyeri 17 inç",
    "category": "saddle",
    "categoryName": "Eyer",
    "parentCategory": "tack",
    "brand": "Antares",
    "model": null,
    "sizeLabel": "17\"",
    "condition": "good",
    "priceAmount": 64000,
    "priceCurrency": "TRY",
    "priceType": "negotiable",
    "priceUnit": "item",
    "quantity": 1,
    "delivery": "pickup",
    "countryCode": "TR",
    "region": "İzmir",
    "city": "İzmir",
    "sellerHandle": "anadolu-yem",
    "sellerName": "Anadolu Yem",
    "sellerVerification": "none",
    "sellerTrustScore": 0,
    "coverImage": null,
    "isBoosted": false,
    "publishedAt": "2026-08-15T15:17:08.505Z"
  },
  {
    "id": "f55e85f2-51fa-4770-91ad-0effb325e35c",
    "slug": "wintec-500-all-purpose-17-5-inc-msuirqwt",
    "title": "Wintec 500 All Purpose 17.5 inç",
    "category": "saddle",
    "categoryName": "Eyer",
    "parentCategory": "tack",
    "brand": "Wintec",
    "model": "500 AP",
    "sizeLabel": "17.5\"",
    "condition": "like_new",
    "priceAmount": 18500,
    "priceCurrency": "TRY",
    "priceType": "negotiable",
    "priceUnit": "item",
    "quantity": 1,
    "delivery": "both",
    "countryCode": "TR",
    "region": "İstanbul",
    "city": "İstanbul",
    "sellerHandle": "saraciye-atolyesi",
    "sellerName": "Saraciye Atölyesi",
    "sellerVerification": "none",
    "sellerTrustScore": 0,
    "coverImage": null,
    "isBoosted": false,
    "publishedAt": "2026-08-15T15:17:08.487Z"
  },
  {
    "id": "99ce00f2-d6f7-4a69-9ebd-1e6eeef455bc",
    "slug": "wintec-500-all-purpose-17-5-inc-msuikl0i",
    "title": "Wintec 500 All Purpose 17.5 inc",
    "category": "saddle",
    "categoryName": "Eyer",
    "parentCategory": "tack",
    "brand": "Wintec",
    "model": "500 AP",
    "sizeLabel": "17.5\"",
    "condition": "like_new",
    "priceAmount": 18500,
    "priceCurrency": "TRY",
    "priceType": "negotiable",
    "priceUnit": "item",
    "quantity": 1,
    "delivery": "both",
    "countryCode": "TR",
    "region": "Istanbul",
    "city": "Istanbul",
    "sellerHandle": "satici-test10",
    "sellerName": "Satici Test",
    "sellerVerification": "none",
    "sellerTrustScore": 0,
    "coverImage": null,
    "isBoosted": false,
    "publishedAt": "2026-08-15T15:11:34.290Z"
  }
];

/** §13's product taxonomy: 8 groups, 28 leaves. */
export const DEMO_PRODUCT_CATEGORIES: (ReferenceItem & {
  parentCode: string | null;
  activeCount: number;
})[] = [
  {
    "code": "tack",
    "name": "Koşum ve saraciye",
    "parentCode": null,
    "activeCount": 6
  },
  {
    "code": "saddle",
    "name": "Eyer",
    "parentCode": "tack",
    "activeCount": 3
  },
  {
    "code": "bridle",
    "name": "Başlık ve dizgin",
    "parentCode": "tack",
    "activeCount": 1
  },
  {
    "code": "bit",
    "name": "Gem",
    "parentCode": "tack",
    "activeCount": 1
  },
  {
    "code": "girth",
    "name": "Kolan ve üzengi",
    "parentCode": "tack",
    "activeCount": 0
  },
  {
    "code": "saddle_pad",
    "name": "Eyer altı",
    "parentCode": "tack",
    "activeCount": 1
  },
  {
    "code": "harness",
    "name": "Araba koşumu",
    "parentCode": "tack",
    "activeCount": 0
  },
  {
    "code": "rider",
    "name": "Binici ekipmanı",
    "parentCode": null,
    "activeCount": 2
  },
  {
    "code": "helmet",
    "name": "Kask",
    "parentCode": "rider",
    "activeCount": 1
  },
  {
    "code": "riding_boots",
    "name": "Binici çizmesi",
    "parentCode": "rider",
    "activeCount": 1
  },
  {
    "code": "breeches",
    "name": "Pantolon ve ceket",
    "parentCode": "rider",
    "activeCount": 0
  },
  {
    "code": "body_protector",
    "name": "Koruyucu yelek",
    "parentCode": "rider",
    "activeCount": 0
  },
  {
    "code": "gloves_spurs",
    "name": "Eldiven, mahmuz, kamçı",
    "parentCode": "rider",
    "activeCount": 0
  },
  {
    "code": "horse_care",
    "name": "At bakımı",
    "parentCode": null,
    "activeCount": 5
  },
  {
    "code": "horse_boots",
    "name": "At tozluğu ve bandaj",
    "parentCode": "horse_care",
    "activeCount": 1
  },
  {
    "code": "rugs",
    "name": "Battaniye ve çul",
    "parentCode": "horse_care",
    "activeCount": 1
  },
  {
    "code": "grooming",
    "name": "Tımar malzemeleri",
    "parentCode": "horse_care",
    "activeCount": 1
  },
  {
    "code": "supplements",
    "name": "Takviye ve vitamin",
    "parentCode": "horse_care",
    "activeCount": 1
  },
  {
    "code": "farrier_tools",
    "name": "Nal ve tırnak bakımı",
    "parentCode": "horse_care",
    "activeCount": 1
  },
  {
    "code": "feed",
    "name": "Yem ve altlık",
    "parentCode": null,
    "activeCount": 3
  },
  {
    "code": "hay",
    "name": "Kuru ot ve yonca",
    "parentCode": "feed",
    "activeCount": 1
  },
  {
    "code": "grain",
    "name": "Yem ve kesif yem",
    "parentCode": "feed",
    "activeCount": 1
  },
  {
    "code": "bedding",
    "name": "Altlık ve talaş",
    "parentCode": "feed",
    "activeCount": 1
  },
  {
    "code": "stable",
    "name": "Ahır ve çit",
    "parentCode": null,
    "activeCount": 4
  },
  {
    "code": "fencing",
    "name": "Çit ve tel",
    "parentCode": "stable",
    "activeCount": 2
  },
  {
    "code": "stalls",
    "name": "Boks ve panel",
    "parentCode": "stable",
    "activeCount": 1
  },
  {
    "code": "waterer",
    "name": "Suluk ve yemlik",
    "parentCode": "stable",
    "activeCount": 1
  },
  {
    "code": "barn_equipment",
    "name": "Ahır ekipmanı",
    "parentCode": "stable",
    "activeCount": 0
  },
  {
    "code": "arena",
    "name": "Manej ve antrenman",
    "parentCode": null,
    "activeCount": 2
  },
  {
    "code": "jumps",
    "name": "Engel ve sırık",
    "parentCode": "arena",
    "activeCount": 1
  },
  {
    "code": "footing",
    "name": "Zemin ve bakım",
    "parentCode": "arena",
    "activeCount": 0
  },
  {
    "code": "lunging",
    "name": "Longe ekipmanı",
    "parentCode": "arena",
    "activeCount": 1
  },
  {
    "code": "transport",
    "name": "Nakliye ve römork",
    "parentCode": null,
    "activeCount": 1
  },
  {
    "code": "trailer",
    "name": "Römork ve at kamyonu",
    "parentCode": "transport",
    "activeCount": 1
  },
  {
    "code": "transport_gear",
    "name": "Nakliye ekipmanı",
    "parentCode": "transport",
    "activeCount": 0
  },
  {
    "code": "other_product",
    "name": "Diğer",
    "parentCode": null,
    "activeCount": 0
  }
];
