-- ONLY HORSES · reference data seed (spec §9)
-- Idempotent: safe to re-run. Loaded by `pnpm seed:ref`.

-- ============================================================
-- DISCIPLINES (§9.1 — 26 rows)
-- ============================================================
INSERT INTO disciplines (code, name_en, name_tr, name_es, name_de, sort_order) VALUES
  ('show_jumping',        'Show Jumping',          'Engel Atlama',              'Salto de Obstáculos',   'Springreiten',        10),
  ('dressage',            'Dressage',              'Dresaj',                    'Doma Clásica',          'Dressur',             20),
  ('eventing',            'Eventing',              'Üçlü Yarışma',              'Concurso Completo',     'Vielseitigkeit',      30),
  ('endurance',           'Endurance',             'Dayanıklılık',              'Raid',                  'Distanzreiten',       40),
  ('hunter',              'Hunter',                'Hunter',                    'Hunter',                'Hunter',              50),
  ('equitation',          'Equitation',            'Binicilik Tekniği',         'Equitación',            'Reitkunst',           60),
  ('western_pleasure',    'Western Pleasure',      'Western Pleasure',          'Western Pleasure',      'Western Pleasure',    70),
  ('reining',             'Reining',               'Reining',                   'Reining',               'Reining',             80),
  ('cutting',             'Cutting',               'Cutting',                   'Cutting',               'Cutting',             90),
  ('barrel_racing',       'Barrel Racing',         'Varil Yarışı',              'Carrera de Barriles',   'Barrel Racing',      100),
  ('roping',              'Roping',                'Kement',                    'Roping',                'Roping',             110),
  ('trail',               'Trail',                 'Doğa Sürüşü',               'Trail',                 'Trail',              120),
  ('working_equitation',  'Working Equitation',    'Working Equitation',        'Equitación de Trabajo', 'Working Equitation', 130),
  ('horsemanship',        'Horsemanship',          'At Yönetimi',               'Horsemanship',          'Horsemanship',       140),
  ('natural_horsemanship','Natural Horsemanship',  'Doğal Binicilik',           'Doma Natural',          'Natural Horsemanship',150),
  ('driving',             'Driving',               'Koşum',                     'Enganche',              'Fahren',             160),
  ('vaulting',            'Vaulting',              'Voltij',                    'Volteo',                'Voltigieren',        170),
  ('polo',                'Polo',                  'Polo',                      'Polo',                  'Polo',               180),
  ('racing_flat',         'Flat Racing',           'Düz Koşu',                  'Carreras Lisas',        'Galopprennen',       190),
  ('racing_harness',      'Harness Racing',        'Koşum Yarışı',              'Carreras al Trote',     'Trabrennen',         200),
  ('rahvan',              'Rahvan Racing',         'Rahvan Yarışı',             'Carreras Rahvan',       'Rahvan-Rennen',      210),
  ('cirit',               'Cirit (Javelin)',       'Cirit',                     'Cirit',                 'Cirit',              220),
  ('gaited',              'Gaited',                'Yürüyüşlü',                 'Marcha',                'Gangpferde',         230),
  ('therapy_riding',      'Therapeutic Riding',    'Terapi Biniciliği',         'Equinoterapia',         'Therapeutisches Reiten', 240),
  ('breeding',            'Breeding',              'Damızlık',                  'Cría',                  'Zucht',              250),
  ('leisure',             'Leisure',               'Hobi / Gezinti',            'Ocio',                  'Freizeit',           260)
ON CONFLICT (code) DO UPDATE SET
  name_en = EXCLUDED.name_en, name_tr = EXCLUDED.name_tr,
  name_es = EXCLUDED.name_es, name_de = EXCLUDED.name_de,
  sort_order = EXCLUDED.sort_order;

-- ============================================================
-- SERVICE CATEGORIES (§9.3 — 22 rows)
-- ============================================================
INSERT INTO service_categories (code, name_en, name_tr, name_es, name_de, icon, sort_order) VALUES
  ('training',           'Training',            'Eğitim',              'Doma',                  'Ausbildung',        'whistle',      10),
  ('riding_lessons',     'Riding Lessons',      'Binicilik Dersi',     'Clases de Equitación',  'Reitunterricht',    'graduation',   20),
  ('boarding',           'Boarding',            'Pansiyon',            'Pupilaje',              'Pension',           'home',         30),
  ('transport',          'Transport',           'Nakliye',             'Transporte',            'Transport',         'truck',        40),
  ('veterinary',         'Veterinary',          'Veteriner',           'Veterinaria',           'Tierarzt',          'stethoscope',  50),
  ('farrier',            'Farrier',             'Nalbant',             'Herrador',              'Hufschmied',        'hammer',       60),
  ('dentistry',          'Equine Dentistry',    'Diş Bakımı',          'Odontología Equina',    'Zahnbehandlung',    'tooth',        70),
  ('equine_therapy',     'Equine Therapy',      'At Terapisi',         'Fisioterapia Equina',   'Pferdetherapie',    'sparkles',     80),
  ('chiropractic',       'Chiropractic',        'Kiropraktik',         'Quiropráctica',         'Chiropraktik',      'activity',     90),
  ('saddle_fitting',     'Saddle Fitting',      'Eyer Uyumlama',       'Ajuste de Sillas',      'Sattelanpassung',   'ruler',       100),
  ('tack_repair',        'Tack Repair',         'Takım Tamiri',        'Reparación de Guarnición','Sattlerei',       'wrench',      110),
  ('breeding_stud',      'Breeding / Stud',     'Aygır Hizmeti',       'Semental',              'Deckhengst',        'heart',       120),
  ('embryo_transfer',    'Embryo Transfer',     'Embriyo Transferi',   'Transferencia de Embriones','Embryotransfer','flask',       130),
  ('photography',        'Photography',         'Fotoğraf',            'Fotografía',            'Fotografie',        'camera',      140),
  ('videography',        'Videography',         'Video',               'Videografía',           'Videografie',       'video',       150),
  ('clipping_grooming',  'Clipping & Grooming', 'Tıraş ve Bakım',      'Esquilado y Cuidado',   'Schur & Pflege',    'scissors',    160),
  ('feed_supply',        'Feed Supply',         'Yem Tedariği',        'Suministro de Pienso',  'Futterlieferung',   'wheat',       170),
  ('arena_construction', 'Arena Construction',  'Manej Yapımı',        'Construcción de Pistas','Reitplatzbau',      'construction',180),
  ('insurance',          'Insurance',           'Sigorta',             'Seguros',               'Versicherung',      'shield',      190),
  ('agent_brokerage',    'Agent / Brokerage',   'Aracılık',            'Agente / Intermediación','Vermittlung',      'handshake',   200),
  ('ranch_services',     'Ranch Services',      'Çiftlik Hizmetleri',  'Servicios de Rancho',   'Hofdienste',        'barn',        210),
  ('event_organization', 'Event Organization',  'Etkinlik Organizasyonu','Organización de Eventos','Veranstaltungen','calendar',    220)
ON CONFLICT (code) DO UPDATE SET
  name_en = EXCLUDED.name_en, name_tr = EXCLUDED.name_tr,
  name_es = EXCLUDED.name_es, name_de = EXCLUDED.name_de,
  icon = EXCLUDED.icon, sort_order = EXCLUDED.sort_order;

-- ============================================================
-- BREEDS (§9.2 — 128 rows; Turkish native breeds are mandatory)
-- group_code: arabian | thoroughbred | warmblood | iberian | baroque |
--             stock | gaited | draft | pony | native_tr | asian | other
-- ============================================================
INSERT INTO breeds (code, name_en, name_tr, name_es, name_de, origin, group_code, typical_height_min_cm, typical_height_max_cm, sort_order) VALUES
  -- Turkish native breeds first: launch region is Türkiye (§9.2)
  ('anadolu_yerli',    'Anatolian Native',       'Anadolu Yerli Atı',  'Nativo de Anatolia',   'Anatolisches Landpferd','TR','native_tr',125,145,  1),
  ('uzunyayla',        'Uzunyayla',              'Uzunyayla',          'Uzunyayla',            'Uzunyayla',            'TR','native_tr',148,158,  2),
  ('malakan',          'Malakan',                'Malakan',            'Malakan',              'Malakan',              'TR','native_tr',155,170,  3),
  ('cukurova',         'Çukurova',               'Çukurova',           'Çukurova',             'Çukurova',             'TR','native_tr',140,152,  4),
  ('canik',            'Canik',                  'Canik',              'Canik',                'Canik',                'TR','native_tr',130,142,  5),
  ('trakya',           'Trakya',                 'Trakya',             'Tracia',               'Trakya',               'TR','native_tr',140,155,  6),
  ('rahvan_at',        'Turkish Rahvan',         'Rahvan Atı',         'Rahvan Turco',         'Türkisches Rahvan',    'TR','native_tr',140,155,  7),
  ('turkoman',         'Turkoman',               'Türkmen Atı',        'Turcomano',            'Turkmene',             'TM','asian',    152,163,  8),
  -- Arabian family
  ('arabian',          'Arabian',                'Arap Atı',           'Árabe',                'Araber',               'SA','arabian',  145,155, 10),
  ('anglo_arabian',    'Anglo-Arabian',          'İngiliz-Arap',       'Angloárabe',           'Anglo-Araber',         'FR','arabian',  155,165, 11),
  ('shagya_arabian',   'Shagya Arabian',         'Shagya Arap',        'Shagya Árabe',         'Shagya-Araber',        'HU','arabian',  150,160, 12),
  ('partbred_arabian', 'Part-bred Arabian',      'Melez Arap',         'Árabe Cruzado',        'Teilblutaraber',       'XX','arabian',  148,163, 13),
  ('arabian_egyptian', 'Straight Egyptian Arabian','Mısır Arap Atı',   'Árabe Egipcio',        'Ägyptischer Araber',   'EG','arabian',  145,155, 14),
  -- Racing / sport foundation
  ('thoroughbred',     'Thoroughbred',           'İngiliz Atı (Safkan)','Pura Sangre Inglés',  'Englisches Vollblut',  'GB','thoroughbred',157,173,20),
  ('akhal_teke',       'Akhal-Teke',             'Ahal Teke',          'Akhal-Teke',           'Achal-Tekkiner',       'TM','asian',    152,163, 21),
  ('standardbred',     'Standardbred',           'Standardbred',       'Standardbred',         'Standardbred',         'US','other',    142,170, 22),
  ('selle_francais',   'Selle Français',         'Selle Français',     'Silla Francés',        'Selle Français',       'FR','warmblood',160,175, 23),
  -- Iberian & baroque
  ('andalusian',       'Andalusian (PRE)',       'Endülüs (PRE)',      'Pura Raza Española',   'Andalusier (PRE)',     'ES','iberian',  152,165, 30),
  ('lusitano',         'Lusitano',               'Lusitano',           'Lusitano',             'Lusitano',             'PT','iberian',  152,163, 31),
  ('alter_real',       'Alter Real',             'Alter Real',         'Alter Real',           'Alter Real',           'PT','iberian',  152,162, 32),
  ('menorquin',        'Menorquín',              'Menorka Atı',        'Menorquín',            'Menorquiner',          'ES','iberian',  154,164, 33),
  ('lipizzaner',       'Lipizzaner',             'Lipizzaner',         'Lipizzano',            'Lipizzaner',           'SI','baroque',  150,163, 34),
  ('friesian',         'Friesian',               'Frizyen',            'Frisón',               'Friese',               'NL','baroque',  155,170, 35),
  ('kladruber',        'Kladruber',              'Kladruber',          'Kladrubero',           'Kladruber',            'CZ','baroque',  160,175, 36),
  ('knabstrupper',     'Knabstrupper',           'Knabstrupper',       'Knabstrupper',         'Knabstrupper',         'DK','baroque',  154,166, 37),
  ('frederiksborg',    'Frederiksborg',          'Frederiksborg',      'Frederiksborg',        'Frederiksborger',      'DK','baroque',  154,166, 38),
  -- Warmbloods
  ('hanoverian',       'Hanoverian',             'Hanover',            'Hannoveriano',         'Hannoveraner',         'DE','warmblood',160,175, 40),
  ('holsteiner',       'Holsteiner',             'Holstein',           'Holsteiner',           'Holsteiner',           'DE','warmblood',162,178, 41),
  ('oldenburg',        'Oldenburg',              'Oldenburg',          'Oldenburgués',         'Oldenburger',          'DE','warmblood',162,178, 42),
  ('westphalian',      'Westphalian',            'Westfalya',          'Westfaliano',          'Westfale',             'DE','warmblood',160,175, 43),
  ('trakehner',        'Trakehner',              'Trakehner',          'Trakehner',            'Trakehner',            'DE','warmblood',160,173, 44),
  ('kwpn',             'KWPN (Dutch Warmblood)', 'KWPN (Hollanda)',    'KWPN',                 'KWPN',                 'NL','warmblood',160,175, 45),
  ('belgian_warmblood','Belgian Warmblood',      'Belçika Sıcakkanlısı','Warmblood Belga',     'Belgisches Warmblut',  'BE','warmblood',160,175, 46),
  ('bwp',              'BWP',                    'BWP',                'BWP',                  'BWP',                  'BE','warmblood',160,175, 47),
  ('zangersheide',     'Zangersheide',           'Zangersheide',       'Zangersheide',         'Zangersheide',         'BE','warmblood',162,178, 48),
  ('irish_sport_horse','Irish Sport Horse',      'İrlanda Spor Atı',   'Caballo Deportivo Irlandés','Irisches Sportpferd','IE','warmblood',160,175,49),
  ('danish_warmblood', 'Danish Warmblood',       'Danimarka Sıcakkanlısı','Warmblood Danés',   'Dänisches Warmblut',   'DK','warmblood',160,175, 50),
  ('swedish_warmblood','Swedish Warmblood',      'İsveç Sıcakkanlısı', 'Warmblood Sueco',      'Schwedisches Warmblut','SE','warmblood',160,175, 51),
  ('bavarian',         'Bavarian Warmblood',     'Bavyera',            'Warmblood Bávaro',     'Bayerisches Warmblut', 'DE','warmblood',158,172, 52),
  ('rheinlander',      'Rhinelander',            'Rheinländer',        'Renano',               'Rheinländer',          'DE','warmblood',160,173, 53),
  ('mecklenburger',    'Mecklenburger',          'Mecklenburg',        'Mecklemburgués',       'Mecklenburger',        'DE','warmblood',158,172, 54),
  ('brandenburger',    'Brandenburger',          'Brandenburg',        'Brandeburgués',        'Brandenburger',        'DE','warmblood',158,172, 55),
  ('sachsen_anhalt',   'Saxony-Anhalt',          'Saksonya-Anhalt',    'Sajonia-Anhalt',       'Sachsen-Anhaltiner',   'DE','warmblood',158,172, 56),
  ('hessian',          'Hessian',                'Hessen',             'Hessiano',             'Hessisches Warmblut',  'DE','warmblood',158,172, 57),
  ('wurttemberger',    'Württemberger',          'Württemberg',        'Wurtemburgués',        'Württemberger',        'DE','warmblood',158,172, 58),
  ('polish_warmblood', 'Polish Warmblood',       'Polonya Sıcakkanlısı','Warmblood Polaco',    'Polnisches Warmblut',  'PL','warmblood',158,172, 59),
  ('malopolski',       'Małopolski',             'Malopolski',         'Małopolski',           'Malopolski',           'PL','warmblood',155,168, 60),
  ('wielkopolski',     'Wielkopolski',           'Wielkopolski',       'Wielkopolski',         'Wielkopolski',         'PL','warmblood',158,170, 61),
  ('hungarian_sport',  'Hungarian Sport Horse',  'Macar Spor Atı',     'Caballo Deportivo Húngaro','Ungarisches Sportpferd','HU','warmblood',158,172,62),
  ('czech_warmblood',  'Czech Warmblood',        'Çek Sıcakkanlısı',   'Warmblood Checo',      'Tschechisches Warmblut','CZ','warmblood',158,172, 63),
  ('sella_italiano',   'Sella Italiano',         'İtalyan Eyer Atı',   'Silla Italiano',       'Sella Italiano',       'IT','warmblood',160,172, 64),
  ('finnhorse',        'Finnhorse',              'Fin Atı',            'Caballo Finlandés',    'Finnpferd',            'FI','other',    153,163, 65),
  ('russian_don',      'Don',                    'Don Atı',            'Don',                  'Don-Pferd',            'RU','other',    155,165, 66),
  ('budyonny',         'Budyonny',               'Budyonny',           'Budyonny',             'Budjonny',             'RU','other',    160,170, 67),
  ('orlov_trotter',    'Orlov Trotter',          'Orlov Tırısçısı',    'Trotón Orlov',         'Orlow-Traber',         'RU','other',    158,170, 68),
  ('kabardin',         'Kabardin',               'Kabardey',           'Kabardino',            'Kabardiner',           'RU','asian',    150,160, 69),
  ('karabair',         'Karabair',               'Karabair',           'Karabair',             'Karabair',             'UZ','asian',    145,155, 70),
  ('karabakh',         'Karabakh',               'Karabağ Atı',        'Karabaj',              'Karabach',             'AZ','asian',    138,150, 71),
  ('marwari',          'Marwari',                'Marwari',            'Marwari',              'Marwari',              'IN','asian',    142,163, 72),
  ('kathiawari',       'Kathiawari',             'Kathiawari',         'Kathiawari',           'Kathiawari',           'IN','asian',    140,152, 73),
  ('barb',             'Barb',                   'Berberi Atı',        'Barbo',                'Berber',               'MA','other',    145,157, 74),
  ('arabian_barb',     'Arab-Barb',              'Arap-Berberi',       'Árabe-Barbo',          'Araber-Berber',        'MA','other',    147,157, 75),
  -- Stock / western
  ('quarter_horse',    'American Quarter Horse', 'Quarter Horse',      'Cuarto de Milla',      'Quarter Horse',        'US','stock',    142,163, 80),
  ('paint',            'American Paint Horse',   'Paint Horse',        'Paint Horse',          'Paint Horse',          'US','stock',    142,163, 81),
  ('appaloosa',        'Appaloosa',              'Appaloosa',          'Appaloosa',            'Appaloosa',            'US','stock',    142,163, 82),
  ('mustang',          'Mustang',                'Mustang',            'Mustang',              'Mustang',              'US','stock',    137,155, 83),
  ('morgan',           'Morgan',                 'Morgan',             'Morgan',               'Morgan',               'US','stock',    142,155, 84),
  ('pony_of_americas', 'Pony of the Americas',   'Amerika Midillisi',  'Pony de las Américas', 'Pony of the Americas', 'US','pony',     117,142, 85),
  ('appendix',         'Appendix Quarter Horse', 'Appendix',           'Appendix',             'Appendix',             'US','stock',    152,168, 86),
  ('criollo',          'Criollo',                'Criollo',            'Criollo',              'Criollo',              'AR','stock',    138,150, 87),
  ('mangalarga',       'Mangalarga Marchador',   'Mangalarga Marchador','Mangalarga Marchador','Mangalarga Marchador', 'BR','gaited',   142,157, 88),
  ('peruvian_paso',    'Peruvian Paso',          'Peru Paso',          'Caballo Peruano de Paso','Paso Peruano',       'PE','gaited',    142,152, 89),
  ('paso_fino',        'Paso Fino',              'Paso Fino',          'Paso Fino',            'Paso Fino',            'PR','gaited',   132,152, 90),
  ('azteca',           'Azteca',                 'Azteca',             'Azteca',               'Azteca',               'MX','stock',    147,163, 91),
  -- Gaited
  ('tennessee_walker', 'Tennessee Walking Horse','Tennessee Walker',   'Tennessee Walker',     'Tennessee Walker',     'US','gaited',   147,170, 95),
  ('missouri_fox_trotter','Missouri Fox Trotter','Missouri Fox Trotter','Missouri Fox Trotter','Missouri Fox Trotter', 'US','gaited',   142,163, 96),
  ('rocky_mountain',   'Rocky Mountain Horse',   'Rocky Mountain',     'Rocky Mountain',       'Rocky Mountain Horse', 'US','gaited',   142,163, 97),
  ('american_saddlebred','American Saddlebred',  'American Saddlebred','Saddlebred Americano', 'American Saddlebred',  'US','gaited',   152,163, 98),
  ('icelandic',        'Icelandic Horse',        'İzlanda Atı',        'Caballo Islandés',     'Islandpferd',          'IS','gaited',   130,145, 99),
  ('kentucky_mountain','Kentucky Mountain Saddle Horse','Kentucky Mountain','Kentucky Mountain','Kentucky Mountain',   'US','gaited',   135,155,100),
  ('campolina',        'Campolina',              'Campolina',          'Campolina',            'Campolina',            'BR','gaited',   150,165,101),
  -- Draft
  ('percheron',        'Percheron',              'Percheron',          'Percherón',            'Percheron',            'FR','draft',    155,183,110),
  ('clydesdale',       'Clydesdale',             'Clydesdale',         'Clydesdale',           'Clydesdale',           'GB','draft',    163,183,111),
  ('shire',            'Shire',                  'Shire',              'Shire',                'Shire',                'GB','draft',    168,190,112),
  ('belgian_draft',    'Belgian Draft',          'Belçika Ağır Atı',   'Caballo Belga',        'Brabanter',            'BE','draft',    163,178,113),
  ('ardennes',         'Ardennes',               'Ardennes',           'Ardenés',              'Ardenner',             'BE','draft',    155,163,114),
  ('suffolk_punch',    'Suffolk Punch',          'Suffolk Punch',      'Suffolk Punch',        'Suffolk Punch',        'GB','draft',    163,175,115),
  ('noriker',          'Noriker',                'Noriker',            'Nórico',               'Noriker',              'AT','draft',    155,168,116),
  ('haflinger',        'Haflinger',              'Haflinger',          'Haflinger',            'Haflinger',            'IT','draft',    137,152,117),
  ('black_forest',     'Black Forest Horse',     'Kara Orman Atı',     'Caballo de la Selva Negra','Schwarzwälder Fuchs','DE','draft', 145,158,118),
  ('jutland',          'Jutland',                'Jutland',            'Jutlandés',            'Jütländer',            'DK','draft',    152,163,119),
  ('boulonnais',       'Boulonnais',             'Boulonnais',         'Bolonés',              'Boulonnais',           'FR','draft',    155,170,120),
  ('breton',           'Breton',                 'Breton',             'Bretón',               'Bretone',              'FR','draft',    150,163,121),
  ('comtois',          'Comtois',                'Comtois',            'Comtois',              'Comtois',              'FR','draft',    148,163,122),
  ('italian_heavy',    'Italian Heavy Draft',    'İtalyan Ağır Atı',   'Caballo Pesado Italiano','Italienisches Kaltblut','IT','draft',145,163,123),
  ('vladimir_draft',   'Vladimir Heavy Draft',   'Vladimir Ağır Atı',  'Vladimir',             'Wladimir-Schwerzugpferd','RU','draft', 158,170,124),
  -- Ponies
  ('welsh_a',          'Welsh Pony Section A',   'Welsh A',            'Welsh Pony A',         'Welsh A',              'GB','pony',      91,122,130),
  ('welsh_b',          'Welsh Pony Section B',   'Welsh B',            'Welsh Pony B',         'Welsh B',              'GB','pony',     122,137,131),
  ('welsh_c',          'Welsh Pony Section C',   'Welsh C',            'Welsh Pony C',         'Welsh C',              'GB','pony',     122,137,132),
  ('welsh_d',          'Welsh Cob Section D',    'Welsh D (Cob)',      'Welsh Cob D',          'Welsh D',              'GB','pony',     137,155,133),
  ('connemara',        'Connemara',              'Connemara',          'Connemara',            'Connemara',            'IE','pony',     128,148,134),
  ('new_forest',       'New Forest Pony',        'New Forest',         'Poni New Forest',      'New Forest Pony',      'GB','pony',     122,148,135),
  ('shetland',         'Shetland Pony',          'Shetland Midillisi', 'Poni Shetland',        'Shetlandpony',         'GB','pony',      71,107,136),
  ('dartmoor',         'Dartmoor Pony',          'Dartmoor',           'Poni Dartmoor',        'Dartmoor Pony',        'GB','pony',     114,127,137),
  ('exmoor',           'Exmoor Pony',            'Exmoor',             'Poni Exmoor',          'Exmoor Pony',          'GB','pony',     114,127,138),
  ('dales',            'Dales Pony',             'Dales',              'Poni Dales',           'Dales Pony',           'GB','pony',     137,145,139),
  ('fell',             'Fell Pony',              'Fell',               'Poni Fell',            'Fell Pony',            'GB','pony',     132,142,140),
  ('highland',         'Highland Pony',          'Highland',           'Poni Highland',        'Highland Pony',        'GB','pony',     132,148,141),
  ('fjord',            'Norwegian Fjord',        'Fiyort Atı',         'Fiordo Noruego',       'Fjordpferd',           'NO','pony',     135,150,142),
  ('gotland',          'Gotland Pony',           'Gotland',            'Poni Gotland',         'Gotlandpony',          'SE','pony',     115,130,143),
  ('hucul',            'Hucul Pony',             'Hucul',              'Poni Hucul',           'Huzule',               'PL','pony',     130,145,144),
  ('german_riding_pony','German Riding Pony',    'Alman Binicilik Midillisi','Poni Alemán de Silla','Deutsches Reitpony','DE','pony',  138,148,145),
  ('pottok',           'Pottok',                 'Pottok',             'Pottoka',              'Pottok',               'ES','pony',     115,132,146),
  ('camargue',         'Camargue',               'Camargue',           'Camargués',            'Camargue-Pferd',       'FR','other',    135,150,147),
  ('falabella',        'Falabella',              'Falabella',          'Falabella',            'Falabella',            'AR','pony',      63,86, 148),
  ('mini_horse',       'Miniature Horse',        'Mini At',            'Caballo Miniatura',    'Miniaturpferd',        'US','pony',      66,97, 149),
  ('caspian',          'Caspian',                'Hazar Atı',          'Caspio',               'Caspian',              'IR','pony',     100,124,150),
  -- Colour / type registries and catch-alls
  ('gypsy_vanner',     'Gypsy Vanner',           'Gypsy Vanner',       'Gypsy Vanner',         'Tinker',               'GB','draft',    137,163,160),
  ('irish_cob',        'Irish Cob',              'İrlanda Cob',        'Cob Irlandés',         'Irish Cob',            'IE','draft',    135,160,161),
  ('pinto',            'Pinto',                  'Pinto',              'Pinto',                'Pinto',                'US','other',    142,168,162),
  ('palomino',         'Palomino',               'Palomino',           'Palomino',             'Palomino',             'US','other',    142,168,163),
  ('buckskin',         'Buckskin',               'Buckskin',           'Bayo',                 'Falbe',                'US','other',    142,168,164),
  ('cob',              'Cob',                    'Cob',                'Cob',                  'Cob',                  'GB','other',    135,155,165),
  ('hackney',          'Hackney',                'Hackney',            'Hackney',              'Hackney',              'GB','other',    142,163,166),
  ('cleveland_bay',    'Cleveland Bay',          'Cleveland Bay',      'Cleveland Bay',        'Cleveland Bay',        'GB','other',    160,170,167),
  ('irish_draught',    'Irish Draught',          'İrlanda Draught',    'Irish Draught',        'Irish Draught',        'IE','other',    155,170,168),
  ('lusitano_cross',   'Lusitano Cross',         'Lusitano Melezi',    'Cruce Lusitano',       'Lusitano-Kreuzung',    'PT','iberian',  152,165,169),
  ('sport_pony',       'Sport Pony',             'Spor Midillisi',     'Poni Deportivo',       'Sportpony',            'XX','pony',     130,148,170),
  ('crossbred',        'Crossbred',              'Melez',              'Mestizo',              'Kreuzung',             NULL,'other',    120,180,900),
  ('unknown',          'Unknown',                'Bilinmiyor',         'Desconocido',          'Unbekannt',            NULL,'other',    NULL,NULL,999)
ON CONFLICT (code) DO UPDATE SET
  name_en = EXCLUDED.name_en, name_tr = EXCLUDED.name_tr,
  name_es = EXCLUDED.name_es, name_de = EXCLUDED.name_de,
  origin = EXCLUDED.origin, group_code = EXCLUDED.group_code,
  typical_height_min_cm = EXCLUDED.typical_height_min_cm,
  typical_height_max_cm = EXCLUDED.typical_height_max_cm,
  sort_order = EXCLUDED.sort_order;
